### ISSUE TITLE
ESP IDE 3.0.0 Disable in place editor content assist (IEP-1319)

### ISSUE THREAD

**Issue by C-basstien** [espressif/idf-eclipse-plugin#1043]
Dear ESP team,

I have just tried your new ESP-IDE 3.0.0: https://github.com/espressif/idf-installer/releases/tag/espressif-ide-3.0.0-esp-idf-5.2.2
The new C/C++ editor setting activate a content assist on functions parameters, where it show function argument name.
I highlighted in yellow in the following pictures, the arguments hint that the editor display:
![image](https://github.com/espressif/idf-eclipse-plugin/assets/22253062/0e3a26c9-8c21-4feb-8fea-bd70f992411e)
How to disable this option ?

Thank you

**Comment by kolipakakondal** [comment]
Hi @C-basstien Add the following settings to .clangd file.

```
InlayHints:
 Enabled: No
```

![image](https://github.com/user-attachments/assets/c8b93bb9-1153-430a-bc5d-1124ac8e0c70)

**Comment by C-basstien** [comment]
Thanks a lot that worked.
