### ISSUE TITLE
sdkconfig SPI RAM config are not available (IEP-212)

### ISSUE THREAD

**Issue by ftoyon** [espressif/idf-eclipse-plugin#105]
In 'SDK Configuration' page when we check 'Support for external, SPI-connected RAM' in 'ES32-Specific' the 'SPI RAM config' are not available.

![image](https://user-images.githubusercontent.com/1707426/87566837-d4d6f100-c6c3-11ea-9248-4634a8e469f9.png)
![image](https://user-images.githubusercontent.com/1707426/87567932-26cc4680-c6c5-11ea-9b4c-eac4e5a6e1e6.png)

IDF Eclipse Plugin Version: 1.1.1.202006040612

IDF Version: 4.0.1

**Comment by kolipakakondal** [comment]
Thanks for reporting, let us check.

**Comment by kolipakakondal** [comment]
Hi All,

We have fixed this issue with our recent releases, Please check this here https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.2.1

Use Java 11 and above, Eclipse 2020-06(4.16) to work with the IDF Eclipse plugin

Thanks

**Comment by ftoyon** [comment]
Hi !

After update plugin to the version 1.2.1
We have this error
![image](https://user-images.githubusercontent.com/1707426/91334546-6eb7b080-e7cf-11ea-933e-11f71d589147.png)

And in Json Configuration Server Console:
```
The following Python requirements are not satisfied:

esp-windows-curses; sys_platform == 'win32'

To install the missing packages, please run "C:\Users\Frederic\esp32\esp-idf-v4.1\install.bat"


ESP-IDF v4.1
```
I'm under Windows with eclipse 2020-06 and java 11.0.7 and phyton 3.8.

I get the esp-idf 4.1yesterday by git clone and after I run install.bat and export.bat

The `idf.py menuconfig` is working.
