### ISSUE TITLE
Project Launch Bar Missing  (IEP-1324)

### ISSUE THREAD

**Issue by cjdg** [espressif/idf-eclipse-plugin#1050]
**Describe the bug**
There is no Project Launch Bar on Eclipse.

**To Reproduce**
Install Espressif IDF plugin
Create a new project
No toolbar

**Expected behavior**
Its supposed to have a toolbar for building and running the project.

**Screenshots**
![imagen](https://github.com/user-attachments/assets/c8c6d089-b5b7-4780-915d-40eedb6a2c55)

**Espressif-IDE Product Information:**
Espressif > Product Information (Copy content from the console and attach as a file)

**Eclipse Error log:** 

[Error.log](https://github.com/user-attachments/files/17016236/Error.log)

**Comment by sigmaaa** [comment]
Hi @cjdg,
Please take a look if you have the launch bar enabled in preferences:
1. In eclipse go to Window -> Preferences -> Run/Debug -> Launching -> Launch Bar
![image](https://github.com/user-attachments/assets/e2d5ba28-20db-4aa6-b825-40efd4735520)

**Comment by cjdg** [comment]
![imagen](https://github.com/user-attachments/assets/0715742e-293f-46ee-acf2-0d1ec7a4bea1)

**Comment by cjdg** [comment]
![imagen](https://github.com/user-attachments/assets/6e872d04-3b8e-40dd-982f-45ea6009ca14)

**Comment by sigmaaa** [comment]
Hi @cjdg,
I see Launching is unclicked on your screenshot. The "Launch Bar" option must appear after you click on "Launching"

**Comment by cjdg** [comment]
![imagen](https://github.com/user-attachments/assets/27d193f6-0eef-4bca-b65b-e7a080a46b65)

**Comment by sigmaaa** [comment]
Hi @cjdg,

could you check if the LaunchBar is installed in the CDT plugin? Please try the following:

- Go to Install New Software
- Select the CDT update site, for example - https://download.eclipse.org/tools/cdt/releases/latest
- Install the Launchbar plugin if it's missing. Please find the screenshot below.
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/8eefe241-acba-4515-81c7-ababcab00dcb">

**Comment by cjdg** [comment]
that was!!!!, well, now i have the toolbar and works fine, thanks, maybe it has to be writen as a requirement for the plugin, or extend the documentation ?
