### ISSUE TITLE
Eclipse autocomplete does not work (IEP-216)

### ISSUE THREAD

**Issue by sirgrej** [espressif/idf-eclipse-plugin#109]
**Describe the bug**
Eclipse Autocomplete (ctrl. + space) does not work when using espressif plugin. It works for standart gcc libs but not for esp-idf.

- Building +flashing works fine 
- no unresolved inclusion
- no Errors

**To Reproduce**
try to use auto-completion by typing (ctrl. + Space) while coding

**Expected behavior**
Normally I would just add the esp-idf include Path to the Path and Symbols Tab in Project Properties, but this tab is missing in newer eclipse versions

**Environment Information:** 
Eclipse 2020-06
java JDK 11

**ESP-IDF Tools Information:**

* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2019r2-8.2.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51.20170517 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.13.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20190313 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.9.0 (recommended, installed)

**IDF Eclipse Plugin Version:** 
Espressif plugin 1.1.1.202006040612

For v1.1.0 and above: Eclipse > About Eclipse > Click on "espresif" icon

**Comment by kolipakakondal** [comment]
<img width="906" alt="Screenshot 2020-08-12 at 7 46 05 AM" src="https://user-images.githubusercontent.com/8463287/89967770-efbf6580-dc6f-11ea-9c1b-dec0748d4558.png">
<img width="620" alt="Screenshot 2020-08-12 at 7 43 28 AM" src="https://user-images.githubusercontent.com/8463287/89967774-f221bf80-dc6f-11ea-8b02-b5eb5976d096.png">
<img width="617" alt="Screenshot 2020-08-12 at 7 43 19 AM" src="https://user-images.githubusercontent.com/8463287/89967781-f3eb8300-dc6f-11ea-8e6c-ca0518c77af6.png">

Hi @sirgrej 

Could you reset the above preference pages using "**Restore defaults**" and see if it helps?

Thanks

**Comment by sirgrej** [comment]
Hi Kondal, thx for your reply,

I have a fresh eclipse install, so restoring to defaults did not help as expected, but checking the "**Parsing-based Proposal**" option in **Editor ->Content Assist -> Advanced** solved to Problem

![Bildschirmfoto vom 2020-08-12 16-23-05](https://user-images.githubusercontent.com/2677476/90027623-076f0c00-dcb9-11ea-83cf-182470b2f2c3.png)

This is strange, I guess something went wrong with the eclipse default settings

Any chance to check these setting while installing the espressif plugin?

**Comment by kolipakakondal** [comment]
By default "Parsing-based Proposal" is selected in the default content assist in Eclipse.
