### ISSUE TITLE
 Workspace location can't include space to create ESP-IDF project (IEP-224)

### ISSUE THREAD

**Issue by zeebak** [espressif/idf-eclipse-plugin#115]
I am unable to create an ESP32 New Project. 

![image](https://user-images.githubusercontent.com/69984922/91128137-3e83eb00-e6c5-11ea-9942-027b765ed863.png)

**Comment by freeride01** [comment]
The path to your workspace (F:\Eclipse Esp\Workspace) contains a space. Try without it - F:\Eclipse_Esp\Workspace for example.

**Comment by kolipakakondal** [comment]
Hi @zeebak 

IDF project name or workspace name with spaces are not allowed.

**Comment by TiSiAi** [comment]
Hello
On macOS Catalina 10.15.6
I have the same problem, but I found the problem linked with the default Eclipse folder project.
My default project workspace has a space on his name and if change change the path without space when I try to create a new est project it is impossible.
I I launch eclipse with a default project workspace without space, it is ok !
![Capture d’écran 2020-09-07 à 14 24 10](https://user-images.githubusercontent.com/39954555/92387940-b36c1180-f116-11ea-98af-dd0d9ed380ad.png)
![Capture d’écran 2020-09-07 à 14 24 28](https://user-images.githubusercontent.com/39954555/92387946-b830c580-f116-11ea-98a1-c5248a83ed97.png)
![Capture d’écran 2020-09-07 à 14 25 21](https://user-images.githubusercontent.com/39954555/92387949-bbc44c80-f116-11ea-9f40-0df4dfe4ac25.png)
![Capture d’écran 2020-09-07 à 14 26 32](https://user-images.githubusercontent.com/39954555/92387962-bff06a00-f116-11ea-877a-845001682f53.png)

**Comment by kolipakakondal** [comment]
> ![Capture d’écran 2020-09-07 à 14 24 28](https://user-images.githubusercontent.com/39954555/92387946-b830c580-f116-11ea-98a1-c5248a83ed97.png)
This is a bug. Thanks for providing the details. We will fix this in the next release.
