### ISSUE TITLE
Application Size Analysis Fails (IEP-228)

### ISSUE THREAD

**Issue by curiousmuch** [espressif/idf-eclipse-plugin#117]
**Describe the bug**
The Application Size Analysis Tools fails. The attached log is generated. 

[Eclipse_Information_20200830.txt](https://github.com/espressif/idf-eclipse-plugin/files/5147540/Eclipse_Information_20200830.txt)

**To Reproduce**
1. Clone ESP32-IDF
2. Checkout v4.1 
3. Install Tools 
4. Install Eclipse 2020-06 
5. Install Espressif Pluging 
6. Import hello_world example and build 
7. Right click on the project and select Application Size Analysis 

**Expected behavior**
What is seen for the ESP-IDF: Application Size Analysis feature in the README. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7798665/91670360-bcdbf500-eaea-11ea-9c4c-78cbf4fcfbea.png)

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)

[Eclipse_Information_20200830.txt](https://github.com/espressif/idf-eclipse-plugin/files/5147538/Eclipse_Information_20200830.txt)

**ESP-IDF Tools Information:**
![image](https://user-images.githubusercontent.com/7798665/91670417-50adc100-eaeb-11ea-92da-db4618ecb879.png)

**IDF Eclipse Plugin Version:** 
![image](https://user-images.githubusercontent.com/7798665/91670385-f4e33800-eaea-11ea-90d1-2703f60a5b9b.png)

**Comment by curiousmuch** [comment]
Please let me know if there is any additional information I can provide.

**Comment by kolipakakondal** [comment]
Hi @curiousmuch

When you encounter an error, please provide the error log as mentioned here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by curiousmuch** [comment]
Attached Sir! 
[Application-Size.log](https://github.com/espressif/idf-eclipse-plugin/files/5166201/Application-Size.log)

**Comment by kolipakakondal** [comment]
Hi @curiousmuch 

What's the IDF version which you're using? I could see the below error in the error log.

```
MESSAGE usage: idf_size - a tool to print IDF elf file sizes [-h]
                                                     [--toolchain-prefix TOOLCHAIN_PREFIX]
                                                     [--json] [--archives]
                                                     [--archive_details ARCHIVE_DETAILS]
                                                     [--files]
                                                     [-o OUTPUT_FILE]
                                                     map_file
idf_size - a tool to print IDF elf file sizes: error: unrecognized arguments: --target esp32
```
