### ISSUE TITLE
OpenOCD / GDB Debugging Plugin Functionality Fails (IEP-229)

### ISSUE THREAD

**Issue by curiousmuch** [espressif/idf-eclipse-plugin#118]
**Describe the bug**
I'm able to start a Debugging Session using the command line options (setup GDB Server and connect Client), but not via Eclipse. Further, even if I start the GDB server in the command line and then attempt to attach using the plug-in functionality, it generates the same error. 

**To Reproduce**
1. Clone ESP-IDF 
2. Checkout v4.1  
3. Install all tools 
4. Install Eclipse 202006 and Espressif Plugin 
5. Import hello_world example and Build
6. Add Debugging Setup 
7. Click Debug :) 

**Expected behavior**
It appears from the plug-in README, it will auto setup a GDB server and connect eclipse to it? Please let me know if this is incorrect?

**Screenshots**
Working w/ command line. 
![image](https://user-images.githubusercontent.com/7798665/91670783-94ee9080-eaee-11ea-88d0-c0028004999c.png)
![image](https://user-images.githubusercontent.com/7798665/91670790-9e77f880-eaee-11ea-8539-70728dec46e5.png)

Failure w/ Eclipse Plugin (local GBD Server) 
![image](https://user-images.githubusercontent.com/7798665/91670803-d2ebb480-eaee-11ea-900e-2a3237c5ee6b.png)
![image](https://user-images.githubusercontent.com/7798665/91670842-4b527580-eaef-11ea-9ef8-c61f63a708a3.png)

Failure w/ Eclipse Plugin (Remote GBD Sever) 
![image](https://user-images.githubusercontent.com/7798665/91670834-28c05c80-eaef-11ea-9e86-3981a330a995.png)

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)
[Eclipse_Information_20200830.txt](https://github.com/espressif/idf-eclipse-plugin/files/5147571/Eclipse_Information_20200830.txt)

**ESP-IDF Tools Information:**
Help > Espressif Tools Manager > List Installed Tools
![image](https://user-images.githubusercontent.com/7798665/91670879-92d90180-eaef-11ea-93d6-8e63dc6586fa.png)

**IDF Eclipse Plugin Version:** 
Eclipse > About Eclipse > Installation Details > Installed Software > Search for "espressif"

For v1.1.0 and above: Eclipse > About Eclipse > Click on "espresif" icon

![image](https://user-images.githubusercontent.com/7798665/91670886-a2f0e100-eaef-11ea-82bd-b24bc702b08a.png)

**Comment by curiousmuch** [comment]
Please let me know if there any additional information I can help provide!

**Comment by kolipakakondal** [comment]
Hi @curiousmuch 

Could you please provide the error log as mentioned here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by curiousmuch** [comment]
Absolutely! I'll be able to upload in a few hours. Thanks for the quick response!

**Comment by curiousmuch** [comment]
Absolutely! I'll be able to upload in a few hours. Thanks for the quick response!

**Comment by curiousmuch** [comment]
Sorry for the delay. 
[JTAG-log2.log](https://github.com/espressif/idf-eclipse-plugin/files/5160077/JTAG-log2.log)
[JTAG-log.log](https://github.com/espressif/idf-eclipse-plugin/files/5160078/JTAG-log.log)

I believe these are the logs you want. I wasn't able to get to the office today, but these are the errors setting in the log from previously.

**Comment by kolipakakondal** [comment]
Thanks @curiousmuch for providing the logs.

Could you try this local build and confirm it. Based on that, I'll provide release update.

[com.espressif.idf.update-v1.2.1-1-g20abb88e.zip](https://github.com/espressif/idf-eclipse-plugin/files/5160235/com.espressif.idf.update-v1.2.1-1-g20abb88e.zip)

Please follow the steps from here to install the above build https://github.com/espressif/idf-eclipse-plugin#installing-idf-eclipse-plugin-from-local-archive

**Comment by ammaree** [comment]
I have installed the local build and although we have progress, based on the time taken till it halts and the number of OpenOCD messages, its still fails.

OpenOCD log:
--------------
[20200902 10h00 console log.pdf](https://github.com/espressif/idf-eclipse-plugin/files/5160918/20200902.10h00.console.log.pdf)

Eclipse error message:
-----------------------
<img width="401" alt="Screenshot 2020-09-02 at 09 56 37" src="https://user-images.githubusercontent.com/3227544/91956480-fee08300-ed04-11ea-82bf-c174b14d4fe2.png">

Error log:
---------
<img width="1585" alt="Screenshot 2020-09-02 at 10 08 25" src="https://user-images.githubusercontent.com/3227544/91956550-19b2f780-ed05-11ea-8377-cf0f034b4d40.png">

Error detail:
-----------
<img width="1789" alt="Screenshot 2020-09-02 at 10 07 58" src="https://user-images.githubusercontent.com/3227544/91956587-2899aa00-ed05-11ea-984e-34fe5ea0e33e.png">

**Comment by kolipakakondal** [comment]
Thanks for providing the logs @ammaree 

Here is the problem which still need to be fixed:
1. Go to startup Tab
2. Uncheck `Load executable` as mentioned in the screenshot.(We will document this)
![OpenOCD_startup](https://user-images.githubusercontent.com/8463287/91980882-982f8980-ed45-11ea-88b8-6df575060a5f.png)

**Comment by kolipakakondal** [comment]
Particualr OpenOCD versoins have the following error.

```
Error: cpu0: Failed to write breakpoint instruction (-4)!
Error: cpu0: Failed to add SW breakpoint!
Error: can't add breakpoint: unknown reason
Error: cpu0: Failed to write breakpoint instruction (-4)!
Error: cpu0: Failed to add SW breakpoint!
Error: can't add breakpoint: unknown reason
```

If you have the above issue, please get the latest OpenOCD version and configure it the `Debugger` tab.
Download latest OpenOCD https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20200709


![Screenshot 2020-09-02 at 6 02 37 PM](https://user-images.githubusercontent.com/8463287/91981542-a3cf8000-ed46-11ea-8d8b-5e872cd701f9.png)

**Comment by curiousmuch** [comment]
> Thanks @curiousmuch for providing the logs.
> 
> Could you try this local build and confirm it. Based on that, I'll provide release update.
> 
> [com.espressif.idf.update-v1.2.1-1-g20abb88e.zip](https://github.com/espressif/idf-eclipse-plugin/files/5160235/com.espressif.idf.update-v1.2.1-1-g20abb88e.zip)
> 
> Please follow the steps from here to install the above build https://github.com/espressif/idf-eclipse-plugin#installing-idf-eclipse-plugin-from-local-archive

I'll give this a shot tonight and let you know. Thanks again for the quick response!

**Comment by curiousmuch** [comment]
@kolipakakondal this will work if the startup configuration is modified as suggested above (i.e. disable JTAG load).

**Comment by kolipakakondal** [comment]
@curiousmuch Thanks for verifying this. We will push the update site soon with these changes.

**Comment by curiousmuch** [comment]
Sounds good. Thanks for the quick responses! Do you know if the plug in will support JTAG load in the future? 

Just curious. I can get around it with a custom script.
