### ISSUE TITLE
unresolved libraries (IEP-241)

### ISSUE THREAD

**Issue by Kamalmohamed1** [espressif/idf-eclipse-plugin#126]
i have just downloaded the plugin with a new eclipse and just trying a sample project to make sure all is fine and then this .
![image](https://user-images.githubusercontent.com/71295596/93145577-f4eb5680-f6ec-11ea-9f55-750faf42b106.png)

**Comment by kolipakakondal** [comment]
Hi @Kamalmohamed1 

Project errors will be resolved only after the build.  Can you please check this https://github.com/espressif/idf-eclipse-plugin#BuildApplication.

**Comment by kolipakakondal** [comment]
Closing this issue for now, please report us back if you see the same issue with our recent release. Recently we have released 2.0.0-beta as well, this is fixes for unresolved headers and inclusion issues, please get the latest changes using https://dl.espressif.com/dl/idf-eclipse-plugin/updates/beta/ update site
