### ISSUE TITLE
we have to install esp idf inside a esp folder then it will work otherwise it wont work (IEP-268)

### ISSUE THREAD

**Issue by swaroopbu** [espressif/idf-eclipse-plugin#151]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)

**ESP-IDF Tools Information:**
Help > Espressif Tools Manager > List Installed Tools

**IDF Eclipse Plugin Version:** 
Eclipse > About Eclipse > Installation Details > Installed Software > Search for "espressif"

For v1.1.0 and above: Eclipse > About Eclipse > Click on "espresif" icon

**Comment by kolipakakondal** [comment]
Hi @swaroopbu 

Could you provide a reproducible scenario and details to explain your issue title? 

> we have to install esp idf inside a esp folder then it will work otherwise it wont work

**Comment by kolipakakondal** [comment]
The problem description is not sufficient to troubleshoot the problem, hence closing the issue.
