### ISSUE TITLE
/usr/include among include paths? (IEP-277)

### ISSUE THREAD

**Issue by szekelyisz** [espressif/idf-eclipse-plugin#156]
**Describe the bug**

It looks like Eclipse thinks `/usr/include` is used as an include path which is clearly wrong if you're developing for ESP-IDF.

**To Reproduce**

With eclipse stopped, I grepped my workspace path for `/usr/include` and removed all matching files. Started Eclipse, let the indexer run, and right-click -> _Open Declaration_ on a `setsockopt` call in my code, and `/usr/include/x86_64-linux-gnu/sys/socket.h` opens up. Quit Eclipse, `/usr/include` shows up in 3 files in the workspace again, namely:

* `.metadata/.plugins/org.eclipse.cdt.core/8k_firmware.1605165311487.pdom`
* `.metadata/.plugins/org.eclipse.cdt.core/infoCache/8k_firmware/default.json`
* `.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi`, 2 matches

This seems to be the default?

**Expected behavior**

`$IDF_PATH/components/lwip/lwip/src/include/lwip/sockets.h` opened.

**Environment Information:** 

[eclipse_configuration.txt](https://github.com/espressif/idf-eclipse-plugin/files/5528944/eclipse_configuration.txt)

**ESP-IDF Tools Information:**

```
Executing python /home/szabi/esp/esp-idf/tools/idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20200709 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.0 (recommended, installed)
```

**IDF Eclipse Plugin Version:** 

1.2.2.202009041040

**Comment by kolipakakondal** [comment]
We have released 2.0.0-beta as well, this has fixes for unresolved headers and inclusion issues, please get the latest changes using https://dl.espressif.com/dl/idf-eclipse-plugin/updates/beta/ update site

This also replaces the eclipse CDT parser with the CMake4Eclips parser, and fix some of these issues.
