### ISSUE TITLE
Something wrong in management of ESP-IDF projects (IEP-278)

### ISSUE THREAD

**Issue by ims-fdc** [espressif/idf-eclipse-plugin#157]
**Steps to reproduce the behavior:**
1. Create new Espressif IDF project with template (hello_world in my case)
2. Configure launch target to ESP32
3. Build  (it's OK, the unresolved references disappear on source editor)
4. Flash to target (OK)
5. Close the project
6. Open the project => the sources files show unresolved inclusion 
7. Press build button => the console show the message "Build not configured correctly"
8. Restart Eclipse with project leaved open => build is now functional
9. Restart Eclipse with project closed, then open the project  => the launch configuration seams lost, build button not functional 

![immagine](https://user-images.githubusercontent.com/74706696/99659243-ddb84480-2a60-11eb-83f1-74078298c8dc.png)

10. Restart two times Eclipse to return to step 8 situation

**Environment Information:** 
Platform : Kubuntu 20.04 
Eclipse : version: 2020-09 (4.17.0)

**ESP-IDF Tools Information:**
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* riscv-none-embed-gcc: Toolchain for RISC-V (optional)
  - riscv-none-embed-gcc-8.2.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20200709 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.0 (recommended, installed)

**IDF Eclipse Plugin Version:** 
1.2.3.202010091505

**Comment by kolipakakondal** [comment]
Hello,

All the issues reported were fixed with v2.4.0, please update to the latest and see if that helps.

Thanks
