### ISSUE TITLE
Convert old makefile project into CMake on eclipse (IEP-306)

### ISSUE THREAD

**Issue by matheusmbgeng** [espressif/idf-eclipse-plugin#166]
Hello guys,

I was used to develop using GNU Make on eclipse. For many reasons, i updated my idf and my projects to use CMake now., Using terminal commands, i'm able to compile and flash with CMake the projects that once i did using make system. So, everything is fine with my idf. I also configured my Eclipse plugin and all work's fine if i import a hello_word project. What's haunt me right now is that if i import as "IDF PROJECT" a project that i once developed using GNU Make, this project doesn't appear on the launch configuration.
 I already tried to clear my workspace, delete build folder from the project, and still it doesnt appear. Any hint on that?

**Comment by kolipakakondal** [comment]
Hello, Closing this ticket as Make projects are not supported with idf-eclipse-pluign and there is no plan to support this.
