### ISSUE TITLE
Eclipse 2020-12 Support ? (IEP-326)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/idf-eclipse-plugin#177]
Hello, 

is it planned to support Eclipse 2020-12 ? 

if i install eclipse-embedcpp-2020-12-R-win32-x86\_64.zip it comes with new major release of the Embedded CDT plug-ins (v6.x);

the IDF Plugin still depends on the older 5.x Release CDT. 

so, i guess, need a full roundup for the Plugin to smootly run with 2020-12 right ? 

Thanks,

Franz

**Comment by franz-ms-muc** [comment]
Is it planned to support the Plugins that come with 2020-12?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>
________________________________

**Comment by kolipakakondal** [comment]
Hi @franz-ms-muc 

Our stable version 1.2.4 already supports eclipse 2020-12, and we also made 2.0.0-beta which also supports eclipse 2020-12 along with other fixes and improvements.

Please check the below release notes
1.2.4 https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.2.4

2.0.0-beta https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.0.0-beta
