### ISSUE TITLE
Customize sdkconfig file for esp-idf (IEP-337)

### ISSUE THREAD

**Issue by JosueSanchezEZM** [espressif/idf-eclipse-plugin#189]
Hello, everyone I would like your help to understand how to customize sdkconfig file in order to hide esp-idf component/libraries configuration options. This because I would like to show only those that I added for my personalized components.

![image](https://user-images.githubusercontent.com/76057615/104927782-d681ba00-596f-11eb-9ad0-61e5f7fbd379.png)
 

![image](https://user-images.githubusercontent.com/76057615/104927356-552a2780-596f-11eb-9648-d7d711785dcd.png)

I am using esp-idf realease version 4.2

**Comment by kolipakakondal** [comment]
Hi @JosueSanchezEZM 

The sdkconfig UI editor is based on the `/build/config/kconfig_menus.json` file. This interacts with` idf.py confserver` to update the values.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#build-system-metadata
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#json-configuration-server

**Comment by JosueSanchezEZM** [comment]
Thanks @kolipakakondal I will check your recommendation.

**Comment by kolipakakondal** [comment]
Hi @projectgus  Any thoughts on this?

**Comment by projectgus** [comment]
Hi @JosueSanchezEZM and @kolipakakondal,

I don't think this is something we support. The idea of the Kconfig system is to allow configuring of the entire ESP-IDF project, including all its components.

Is using the filter text field in Eclipse to narrow the selection to only those components enough? Or do you need it to be entirely not shown?

@JosueSanchezEZM can you explain a bit about your use case and why you need this? It seems like you might be looking to "white label" ESP-IDF into a configuration system for a particular product's firmware?

**Comment by JosueSanchezEZM** [comment]
Thanks @projectgus  for your response. What I am looking for is to develop a particular product' firmware as you say. For this, I would like to "redesign" de sdkconfig file to only show my configuration options. Within these configurations, I will use espressif components variables to enable or disable them from my configuration options and to avoid using filter text field to search the specific component configuration option.

Reference Image (Edited from the first comment in this issue):
![image](https://user-images.githubusercontent.com/76057615/106902459-dd762f80-66c6-11eb-95a8-1b6a0bd85841.png)

**Comment by projectgus** [comment]
Hi @JosueSanchezEZM,

I'm afraid that we don't support this use case.

I think probably the best way to achieve what you want would be to edit the code for the configuration viewer in the Eclipse plugin and hard-code it so that it only shows the "EZM Configuration" menu and submenu, then build and distribute a new plugin.

Sorry we can't be of more help.

**Comment by kolipakakondal** [comment]
Please let us know if you need any further help on this. Closing this issue for now.
