### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement click>=5.0 (IEP-345)

### ISSUE THREAD

**Issue by shishui324** [espressif/idf-eclipse-plugin#196]
Java: Javase15 
Eclipse: 2020-12
OS: Windows 10
python: 3.7
esp-idf: 4.2

Hello.

Trying to work with new eclipse plugin, I can't get it. Following readme.md guide, I have everything installed and tools installation console output doesn't show any error. However, when I try to compile any example, console shows that 'requiments.txt' dependencies can't be found.

error log :

Installing tools...
This can take a while. Please be patient.
Executing C:\Users\WAX1WHU\AppData\Local\Programs\Python\Python37\python.exe C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py install all
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, openocd-esp32, ninja, idf-exe, ccache, dfu-util
Skipping xtensa-esp32-elf@esp-2020r3-8.4.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2020r3-8.4.0 (already installed)
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping cmake@3.16.4 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20200709 (already installed)
Skipping ninja@1.10.0 (already installed)
Skipping idf-exe@1.0.1 (already installed)
Skipping ccache@3.7 (already installed)
Skipping dfu-util@0.9 (already installed)

Executing C:\Users\WAX1WHU\AppData\Local\Programs\Python\Python37\python.exe C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py install-python-env
Collecting virtualenv
  Using cached virtualenv-20.4.2-py2.py3-none-any.whl (7.2 MB)
Collecting appdirs<2,>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting filelock<4,>=3.0.0
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting six<2,>=1.9.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading importlib_metadata-3.4.0-py3-none-any.whl (10 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting zipp>=0.5
  Downloading zipp-3.4.0-py3-none-any.whl (5.2 kB)
Collecting typing-extensions>=3.6.4; python_version < "3.8"
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Installing collected packages: appdirs, filelock, six, zipp, typing-extensions, importlib-metadata, distlib, virtualenv
  WARNING: The script virtualenv.exe is installed in 'C:\Users\WAX1WHU\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 importlib-metadata-3.4.0 six-1.15.0 typing-extensions-3.7.4.3 virtualenv-20.4.2 zipp-3.4.0
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\WAX1WHU\AppData\Local\Programs\Python\Python37\python.exe -m pip install --upgrade pip' command.
created virtual environment CPython3.7.9.final.0-64 in 4458ms
  creator CPython3Windows(dest=C:\Users\WAX1WHU\.espressif\python_env\idf4.2_py3.7_env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\WAX1WHU\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Processing c:\software\esp_idf\esp-idf-v4.2\tools\kconfig_new\esp-windows-curses
Requirement already satisfied: setuptools>=21 in c:\users\wax1whu\.espressif\python_env\idf4.2_py3.7_env\lib\site-packages (from -r C:\software\ESP_IDF\esp-idf-v4.2\requirements.txt (line 4)) (52.0.0)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out'))': /simple/click/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out'))': /simple/click/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out'))': /simple/click/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out'))': /simple/click/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1074: The handshake operation timed out'))': /simple/click/
ERROR: Could not find a version that satisfies the requirement click>=5.0
ERROR: No matching distribution found for click>=5.0
Creating a new Python environment in C:\Users\WAX1WHU\.espressif\python_env\idf4.2_py3.7_env
Installing virtualenv
Installing Python packages from C:\software\ESP_IDF\esp-idf-v4.2\requirements.txt
Traceback (most recent call last):
  File "C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py", line 1492, in <module>
    main(sys.argv[1:])
  File "C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py", line 1488, in main
    action_func(args)
  File "C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py", line 1215, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Users\WAX1WHU\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\WAX1WHU\\.espressif\\python_env\\idf4.2_py3.7_env\\Scripts\\python.exe', '-m', 'pip', 'install', '--no-warn-script-location', '-r', 'C:\\software\\ESP_IDF\\esp-idf-v4.2\\requirements.txt']' returned non-zero exit status 1.

Executing C:\Users\WAX1WHU\AppData\Local\Programs\Python\Python37\python.exe C:\software\ESP_IDF\esp-idf-v4.2\tools\idf_tools.py export --format=key-value
OPENOCD_SCRIPTS=C:\Users\WAX1WHU\.espressif\tools\openocd-esp32\v0.10.0-esp32-20200709\openocd-esp32\share\openocd\scripts
IDF_CCACHE_ENABLE=1
IDF_PYTHON_ENV_PATH=C:\Users\WAX1WHU\.espressif\python_env\idf4.2_py3.7_env
PATH=C:\Users\WAX1WHU\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin;C:\Users\WAX1WHU\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\WAX1WHU\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\WAX1WHU\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\WAX1WHU\.espressif\tools\cmake\3.16.4\bin;C:\Users\WAX1WHU\.espressif\tools\openocd-esp32\v0.10.0-esp32-20200709\openocd-esp32\bin;C:\Users\WAX1WHU\.espressif\tools\ninja\1.10.0\;C:\Users\WAX1WHU\.espressif\tools\idf-exe\1.0.1\;C:\Users\WAX1WHU\.espressif\tools\ccache\3.7\;C:\Users\WAX1WHU\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\Users\WAX1WHU\.espressif\python_env\idf4.2_py3.7_env\Scripts;C:\software\ESP_IDF\esp-idf-v4.2\tools;%PATH%
Configured CDT Build Environment variables. You can check Preferences > C/C++ > Build > Environment
Configured CMake toolchain. You can check Preferences > C/C++ > CMake
Install tools completed.

**Comment by diqiu114** [comment]
I have the same problem
