### ISSUE TITLE
Serial monitor backtrace (IEP-350)

### ISSUE THREAD

**Issue by allard-potma** [espressif/idf-eclipse-plugin#200]
The build-in serial monitor does not seem to do a backtrace analysis when a crash occurs. 
When i run "idf.py monitor" in the ESP-IDF terminal in eclipse the backtrace analysis does work.

Is there a reason for this, or is it a bug?

**Comment by kolipakakondal** [comment]
We have released 2.0.0-beta recently, this comes with the idf_monitor.py integration in the eclipse serial monitor, please get the latest changes using https://dl.espressif.com/dl/idf-eclipse-plugin/updates/beta/ update site
