### ISSUE TITLE
FTDI installation instructions for macOS Big Sur with ESP-DEVKIT-V4 (IEP-354)

### ISSUE THREAD

**Issue by ammaree** [espressif/idf-eclipse-plugin#202]
I am trying to follow the instructions for installing the FTDI drivers (2.4.4) but the instructions fail at the point where it comes to install the driver, complaining that it needs to be "approved" in System Preferences.

Having done some homework it seems that Big Sur has Apple drivers preinstalled and that both ports on the FT2232 have USB Serial drivers loaded.

From what I understand the JTAG ports needs to be freed (USB Serial driver removed) up so it can used by OpenOCD with the basic FTDI driver.

I assume the instructions were prepared for an older version of macOS, hence the failure. Can updated instructions please be made available for Big Sur?

**Comment by kolipakakondal** [comment]
@projectgus @projectgus Could you please check if anything has to be updated.

**Comment by ammaree** [comment]
After the last BigSur update the device is now reflected differently again. As in the attached screenshot each of the 2 serial ports are now reflected as 4 separate and differently addressed devices, 8 devices in total.
The normal UART port on my ESP-DEVKIT-V4 is represented by -00003014B and -14301 entries.
<img width="747" alt="Screenshot 2021-03-07 at 10 16 26" src="https://user-images.githubusercontent.com/3227544/110233683-31766d00-7f2e-11eb-95e7-5503b94b65de.png">

/dev/cu.usbserial-00003014B starts and works as per normal:
/dev/tty.usbserial-00003014B starts but warns about hanging if gdb launched, revert to /dev/cu version:
<img width="1094" alt="Screenshot 2021-03-07 at 10 51 36" src="https://user-images.githubusercontent.com/3227544/110234440-26720b80-7f33-11eb-91d7-ae9b19de0978.png">

/dev/tty.usbserial-14301 and /dev/cu.usbserial-14301 both start, issues same warning but then crashes with following message:
<img width="1094" alt="Screenshot 2021-03-07 at 10 49 30" src="https://user-images.githubusercontent.com/3227544/110234373-d09d6380-7f32-11eb-9a13-8aee15026d5f.png">

So, out of all the options presented, how do I get the FTDI port work with OpenOCD?

**Comment by kolipakakondal** [comment]
Hi @ammaree Thanks for the update.

Here is the link for OpenOCD debugging https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/OpenOCD%20Debugging.md

**Comment by ammaree** [comment]
Hi @kolipakakondal @projectgus 

I updated macOS to the latest version 11.2.3, I also checked that the FTDI driver installed is the unmodified version with the original FT2232H_A and FT2232H_B entries.
<img width="434" alt="Screenshot 2021-03-23 at 11 15 38" src="https://user-images.githubusercontent.com/3227544/112122721-3c392f00-8bc9-11eb-91ac-0db8828df82e.png">

I then did a clean install, all the latest tools on Eclipse 2021-03, followed with the instruction linked above to complete the installation and configuration.

However, when I launch the debug configuration it still fails consistently with the following output.
<img width="400" alt="Screenshot 2021-03-23 at 11 07 53" src="https://user-images.githubusercontent.com/3227544/112122961-799dbc80-8bc9-11eb-9e8d-8de9bffe3224.png">

<img width="978" alt="Screenshot 2021-03-23 at 11 10 08" src="https://user-images.githubusercontent.com/3227544/112122984-83272480-8bc9-11eb-897f-b8d5278109b3.png">

Both FTDI posts a & B are shown in the device listing.
<img width="570" alt="Screenshot 2021-03-23 at 11 20 14" src="https://user-images.githubusercontent.com/3227544/112123376-e0bb7100-8bc9-11eb-95b1-cacf68ee4c46.png">

The device can be flashed & monitored using UART port addressed with "-p /dev/cu.usbserial-1442301"

What is currently not clear includes:
a) Must the FTDI driver config still me modified or not?
b) if it is to be modified, can updated instructions please be provided for the latest version of macOS?
c) If not, based on the debug output provided here, what is wrong with my config?

Please, I have wasted a huge amount of time having to debug using printf and cannot continue like this.

**Comment by igrr** [comment]
From the log, it seems that Eclipse is trying to do "load <filename>.elf". @kolipakakondal we need to remove the checkbox "Load executable" in https://github.com/espressif/idf-eclipse-plugin/raw/master/docs/images/OpenOCDDebug_7.png.

@ammaree Please try removing that checkbox.

**Comment by kolipakakondal** [comment]
By default, the "Load executable" option is disabled with the eclipse plugin. It seems to be screenshot is not updated. I just updated the screenshot as well https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/images/OpenOCDDebug_7.png

**Comment by kolipakakondal** [comment]
Closing this issue as the document is updated.
