### ISSUE TITLE
SDKconfig scroll bar not responding

### ISSUE THREAD

**Issue by rdkluijv** [espressif/idf-eclipse-plugin#23]
In the SDK configurator when in the FreeRTOS selection the scroll bar is not responding making it impossible to reach the lower parts of the configurator.
A related feature request: 
Can a horizontal scroll bar be used when the window is not entirely visible?

**Comment by kolipakakondal** [comment]
Issue is fixed with idf-eclipse-plugin-v1.0.0-beta.3

Please get the latest changes using the update site url.
