### ISSUE TITLE
Monitor forces 80-character wide printout. (IEP-408)

### ISSUE THREAD

**Issue by liudr** [espressif/idf-eclipse-plugin#250]
I recently updated my eclipse from 2020-12 to 2021-03 so I thought I should re-install idf-eclipse-plugin. After that, my monitor terminal will only print in 80-char long. I distinctly remember my print outs being as wide as the window but not confined to only about a quarter of the window, exactly 80-char wide. So please fix this! You can't have meaningful printouts forced into multiple lines by this nonsense.

**Comment by kolipakakondal** [comment]
Hi @liudr 

Could you check "Maximum Character Width" option is enabled by chance in eclipse preferences? 

<img width="623" alt="Screenshot 2021-04-20 at 9 33 31 AM" src="https://user-images.githubusercontent.com/8463287/115335793-8824c700-a1bb-11eb-9558-2bdc07678c7d.png">

**Comment by kolipakakondal** [comment]
https://stackoverflow.com/a/46455961/1812235

**Comment by liudr** [comment]
Thanks but it doesn't matter what I have, fixed or not with a 320 char limit. The serial terminal, not console, always displays 80 characters.

**Comment by liudr** [comment]
I installed eclipse on a different computer that doesn't have eclipse or IDF. Same outcome. The option @kolipakakondal posted doesn't affect the behavior of the serial terminal, regardless the settings of the max char width or fixed checkbox. I think this is a genuine bug.

Some observations, on my main computer if I start a project with one of the IDF examples, the dialog that should show markup rendeded on the right half shows up as not rendered. I didn't have this issue on the new install on this other computer or another computer I installed.

**Comment by kolipakakondal** [comment]
This is fixed with release 2.2.0, we have provided an option to configure serial monitor character limit and number of lines.
https://github.com/espressif/idf-eclipse-plugin#esp-idf-serial-monitor-settings

Please get the latest changes using the update site.
