### ISSUE TITLE
Problem to load plugin

### ISSUE THREAD

**Issue by winkste** [espressif/idf-eclipse-plugin#26]
My system environment is:
- OSX Mojave
- Eclipse 
       - Version: 2019-09 R (4.13.0)
       - Build id: 20190917-1200

I'm getting an error during the load process of the plugin. I did a manual download which generated other errors. 

<img width="637" alt="image" src="https://user-images.githubusercontent.com/9803344/68548633-5ec11280-03ef-11ea-9a0e-335dd2f3f1f8.png">

**Comment by winkste** [comment]
while trying to update the manual installed plugin, I got the following message:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/9803344/68548856-b3fe2380-03f1-11ea-9188-fb103b0679b5.png">

**Comment by kolipakakondal** [comment]
It seems to be an issue with your Java version. What's is the Java version that you're using?

It is a common error message reported by the Java Virtual Machine. This is caused when the Java environment does not have information about the HTTPS server to verify that it is a valid website.

Search google with " sun.security.validator.ValidatorException: PKIX path" to find possible answers.

**Comment by winkste** [comment]
Hi.
Thanks for the fast response. I updated my JAVA version to:
<img width="463" alt="Bildschirmfoto 2019-11-11 um 19 31 49" src="https://user-images.githubusercontent.com/9803344/68642575-ea7d9080-050e-11ea-85dc-2ba3c048c8da.png">

That did not solve the problem. Than I tried some of the mentioned solutions found in google:
_Add following to the eclipse.ini file:
- Dorg.eclipse.ecf.provider.filetransfer.excludeContributors=org.eclipse.ecf.provider.filetransfer.httpclient4

None so far worked.

**Comment by kolipakakondal** [comment]
Can you provide eclipse configuration details by following this?
`Eclipse > About Eclipse >Installation details >Configuration`

**Comment by winkste** [comment]
[conf_details.txt](https://github.com/espressif/idf-eclipse-plugin/files/3844602/conf_details.txt)

**Comment by kolipakakondal** [comment]
From the configuration details - I could see, eclipse is still pointing to /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/

That's an issue.  If you don't use jdk1.8.0_25  - straight away you can delete it and restart the eclipse. If you need old jdk for some reason - set new java path to the eclipse.ini as mentioned here https://wiki.eclipse.org/Eclipse.ini

**Comment by winkste** [comment]
Interesting, although I installed the version specified above: 231. Running java -version in the Terminal shows:
<img width="457" alt="Bildschirmfoto 2019-11-14 um 20 10 21" src="https://user-images.githubusercontent.com/9803344/68888302-f6d63900-071a-11ea-95d5-27287a2b5f24.png">

and in the usual installation path of java it's showing:

<img width="408" alt="Bildschirmfoto 2019-11-14 um 20 13 43" src="https://user-images.githubusercontent.com/9803344/68888522-64826500-071b-11ea-9deb-d02737530fcd.png">

So I re-installed JAVA 231 manually by downloading it from oracle:
<img width="460" alt="Bildschirmfoto 2019-11-14 um 20 23 56" src="https://user-images.githubusercontent.com/9803344/68889241-d27b5c00-071c-11ea-9024-80d2e86ed80c.png">

Now it is showing up in the installation path of JAVA, ... look there the server update works!!!
<img width="624" alt="Bildschirmfoto 2019-11-14 um 20 23 41" src="https://user-images.githubusercontent.com/9803344/68889312-f76fcf00-071c-11ea-8848-4a3736f5310f.png">

Thanks Kondal for your support. One issue fixed... several left ;-)

**Comment by winkste** [comment]
Problem solved.
