### ISSUE TITLE
Problem with manual installation of package BETA 3

### ISSUE THREAD

**Issue by winkste** [espressif/idf-eclipse-plugin#27]
Hi.

I tried to install the BETA3 package manually with the following error:

- Installation selection:
<img width="715" alt="Bildschirmfoto 2019-11-12 um 05 58 58" src="https://user-images.githubusercontent.com/9803344/68643444-b8216280-0511-11ea-8cc7-8ec356d483f6.png">
- error message:
<img width="354" alt="Bildschirmfoto 2019-11-12 um 05 59 24" src="https://user-images.githubusercontent.com/9803344/68643470-ca030580-0511-11ea-9bc5-e1f7873afa18.png">

**Comment by kolipakakondal** [comment]
It seems to be you've selected the content.jar, can you select the com.espressif.idf.update-xxx.zip file directly without extracting it.

**Comment by winkste** [comment]
Hi.
Manual installation now worked. Nevertheless, I still figure out other problems wich I will comment in other issue lists. Thanks for your fast response!

<img width="698" alt="Bildschirmfoto 2019-11-13 um 19 15 40" src="https://user-images.githubusercontent.com/9803344/68792151-17cf5900-064b-11ea-83f9-571e34db8fcd.png">

<img width="691" alt="Bildschirmfoto 2019-11-13 um 19 20 43" src="https://user-images.githubusercontent.com/9803344/68792156-1bfb7680-064b-11ea-9335-f2d06388b1ad.png">

**Comment by winkste** [comment]
see my comment above, thanks!
