### ISSUE TITLE
ESP32 WROOM Board debugging using JTAG (IEP-436)

### ISSUE THREAD

**Issue by zoro9091** [espressif/idf-eclipse-plugin#274]
Hi, I am trying to debug my board ESP32 WROOM using JTAG and openocd but I get this error.
![image](https://user-images.githubusercontent.com/16499003/119237906-b4778e80-bb3f-11eb-88bd-900d562ab42e.png)

To be honest I am not sure if this is a configuration problem or the HW itself doesn't support it.
I have just connected the board through USB and I am able to flash and use monitor feature "print stuff to UART over USB" .

In WROVER boards there is a possibility for JTAG debugging over USB with the help of FTDI chip but I suspect this is not possible in WROOM board and I need external debugger like JLINK. What is your opinion?

**Comment by sigmaaa** [comment]
Hi @zoro9091,

yes, you are right. To debug ESP WROOM board you need to have JTAG adapter. Look for one that is compatible with both the voltage levels on the ESP32 as well as with the OpenOCD software. 

You can use JLINK. Also, you can use ESP-Prog https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/hw-reference/ESP-Prog_guide.html

Or you can debug esp wroom board using esp-wrover dev kit, if you have one. 

more info here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/index.html#jtag-debugging-how-it-works
