### ISSUE TITLE
Bug: Launch Configuration DropDown box doesn't update after a project is opened/closed (IEP-442)

### ISSUE THREAD

**Issue by samsam4** [espressif/idf-eclipse-plugin#280]
**Describe the bug**
The Launch DropDown doesn't update its content on change of the open/close condition of projects in current workspace in Eclipse. So if a certain project was closed when Eclipse started, and then opened, the Launch Configuration DropDown box will not show it. 
The only work around I found so far is to close Eclipse (with already opened project of interest) and then close/open again Eclipse

**To Reproduce**
1. Open an Eclipse workspace with couple projects in
2. Close some of the projects
3. Restart Eclipse
4. Open one of the closed projects
5. Observe the content of the Launch configuration DropDown box

**Expected behavior**
On every change of  a project open/close, the Launch configuration DropDown box should update its content with adding or removing accordingly

**Screenshots**
All the projects were closed on startup of Eclipse, the 'blink' project was opened after, but cant be build because it launch configuration is not seen:
![NoLaunchConfig](https://user-images.githubusercontent.com/30199901/120353630-cee40180-c2cf-11eb-951e-93f606fb2390.png)

On startup of Eclipse, the 'esp-idf-ili9340-master' project was opened, later closed;  the 'blink' project was closed, opened after:
![BugConfigurationDropDown](https://user-images.githubusercontent.com/30199901/120353655-d3101f00-c2cf-11eb-8c21-8f70e3bb2814.png)

**Environment Information:** 
Operating System: windows 10

Java Runtime Version: 15.0.2+7-27
Eclipse Version: 4.19.0.v20210303-1800
Eclipse CDT Version: 10.2.0.202012191711
IDF Eclipse Plugin Version: 2.1.0.202104140338
(installed with 2.9beta online installer)

**Eclipse Error log:** 
Don't see any change in Error Log when open/close project or click on Launch DrpDown, but my error log will be attached on other issues I will reporting today

Thanks

**Comment by sigmaaa** [comment]
Hi @samsam4 
fix for it is available in the [latest release ](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.3.0). Thanks
