### ISSUE TITLE
New Eclipse plugin seems shows far less important information in build output (IEP-443)

### ISSUE THREAD

**Issue by samsam4** [espressif/idf-eclipse-plugin#281]
**Describe the bug**
New Eclipse plugin seems shows far less important information in build output than the older version that works with MSYS2. 
The older version that is working with MSYS2 gives way more useful information in 'build' folder in Project explorer window that was pretty enough to track easy problems with include files, dependencies etc.  Now I have such a problem (will start another issue ticket) and is very difficult to trace where the problem comes from :( 
Is this data moved away in some other view/ window or is completely gone?

**To Reproduce**
1. Copy and build 'blink' example with latest plugin (installer 2.9beta)
2. Copy and build 'blink' example with MSYS2 toolchain (I used msys2-i686-20180531/ Eclipse 2019-03 (4.11.0))
3. Open build folder.../main in Project Explorer panes and compare outputs (attached few screenshots)

**Expected behavior**
To have at least the same information for build process what I had with older version

**Screenshots**
Current version:
![NoBuidData](https://user-images.githubusercontent.com/30199901/120365251-330cc280-c2dc-11eb-93dc-98db2e042db4.png)

Older version with NSYS2:
![YesBuidData](https://user-images.githubusercontent.com/30199901/120365264-37d17680-c2dc-11eb-92b8-50166780d2d8.png)

**Environment Information:** 
Operating System: windows 10

Java Runtime Version: 15.0.2+7-27
Eclipse Version: 4.19.0.v20210303-1800
Eclipse CDT Version: 10.2.0.202012191711
IDF Eclipse Plugin Version: 2.1.0.202104140338
(installed with 2.9beta online installer)

Old Version that I Compared with:
Eclipse Version: 2019-03 (4.11.0)
Not sure, but think this was the installer for toolchain msys2-i686-20180531

Thanks

**Comment by alirana01** [comment]
Hi @samsam4 
Sorry for the late response on the issue we were working on the different indexer and linkers issue on the eclipse related to this.

I think what you are looking for can be found in the binaries for the project if you expand the blink.elf file in binaries you can find all the sources and headers information in that binary

![image](https://user-images.githubusercontent.com/85216275/154218618-59d70eda-1d06-4985-b45b-257e64670eea.png)
![image](https://user-images.githubusercontent.com/85216275/154218658-e068069a-b934-4775-a7f4-611751823b24.png)
