### ISSUE TITLE
Feature requests: line width and total number of lines (IEP-467)

### ISSUE THREAD

**Issue by liudr** [espressif/idf-eclipse-plugin#295]
1. Line width is fixed at 80. This is in contrast with most screens that can display hundreds of characters and clips the messages unnecessarily. Please add an option to change line width or fit line width within the display area.
2. Total number of lines. Currently it is fixed at 1000 lines. Most terminal programs offer an option to increase this. Suppose I want to log the printouts for some extended period of time or log lots of outputs that are printed quickly, 1000 lines is not enough. There is no real reason to cap the lines at 1000. Have a much larger number say 65536 or have an option to customize it.

**Comment by fhgeoprospectors** [comment]
totally agree, that 80 char wide is old-tech. it should be unlimited OR adjustable.

**Comment by kolipakakondal** [comment]
Hi @liudr @fhgeoprospectors Fix is available currently on the latest build of the master branch. This is not yet available in the stable release.

If you would like to try please pick this build https://github.com/espressif/idf-eclipse-plugin/suites/3120488433/artifacts/71485600

Install as per the instructions here https://github.com/espressif/idf-eclipse-plugin#installPluginsUsingLocalFile

And configure as per this https://github.com/espressif/idf-eclipse-plugin#esp-idf-serial-monitor-settings

**Comment by alirana01** [comment]
@liudr The feature is now part of the latest release
![image](https://user-images.githubusercontent.com/85216275/129523885-f134a864-62a1-4d81-8376-74657c212c44.png)
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.2.0
