### ISSUE TITLE
After successful build still errors in the errors view and unresolved references (IEP-110)

### ISSUE THREAD

**Issue by winkste** [espressif/idf-eclipse-plugin#30]
Hi.

After I successfully build the hello world project, eclipse is still showing unresolved references and unknown variables. The error view also still mentions errors:

<img width="582" alt="Bildschirmfoto 2019-11-14 um 20 56 35" src="https://user-images.githubusercontent.com/9803344/68891689-a8786880-0721-11ea-9153-c23cc67e0810.png">

Same build:
<img width="651" alt="Bildschirmfoto 2019-11-14 um 21 00 01" src="https://user-images.githubusercontent.com/9803344/68891748-cb0a8180-0721-11ea-9abb-b47c735ffd71.png">

**Comment by kolipakakondal** [comment]
Make sure you select/configure "Launch Target" before triggering the build. Check here https://github.com/espressif/idf-eclipse-plugin#ConfigureLaunchTarget

This will take care of "unresolved references"

**Comment by techny4287** [comment]
I don't know if this helps but I just had this issue as well, I can confirm that specifying a new launch target (even though i had one) resolved the issue. 
After taking a look at my project files, it seems like .cproject file for eclipse is empty or blank when this error appears.

**Comment by sch0bert** [comment]
It didn't help me to make a new launch target, I still have the errors appearing. Regarding your comment @techny4287 about .cproject, I have it with information and doesn't matter regarding this issue. This is something else, else where.

**Comment by kolipakakondal** [comment]
Hi All, IDF Eclipse Plugin v1.0.0-beta5 (Build: 1.0.0.202002120536) is published to the update site. Please get the latest https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/

It has a fix for "unresolved includes" issue. Please check the release notes https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.0.0-beta5

**Comment by sch0bert** [comment]
Hello,

I updated the plug in to the latest and it still unrecognized most of the references:

![image](https://user-images.githubusercontent.com/26800631/74557573-076a9b00-4f26-11ea-8553-5ffd67f9b179.png)

Am I need to do something else?
