### ISSUE TITLE
idf-eclipse-plugin support for esp-idf-v3.3 (IEP-108)

### ISSUE THREAD

**Issue by Sterpa** [espressif/idf-eclipse-plugin#32]
esp-idf-v.3.3 support cmake and had "Long Term Support".
When idf-eclipse-plugin will support esp-idf-v3.3 ?

Without this we cannot use esp-idf with Arduino.h component in Eclipse. Because the only last branch of arduino-esp32 we have is (idf-release/v3.3).

**Comment by kolipakakondal** [comment]
Hello @Sterpa 

IDF Eclipse plugin should now work with the latest version of esp-idf v3.3. 
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v1.0.1

Please check and let us know if see any issues.

**Comment by kolipakakondal** [comment]
Closing this issue as there is no update. However, we have no plan to support esp v3.3 officially with the eclipse plugin.
