### ISSUE TITLE
Error during building the project (IEP-494)

### ISSUE THREAD

**Issue by Dejwuch** [espressif/idf-eclipse-plugin#328]
Hello, 
I was trying to solve this problem by myself but I don't make it.. Please let me help.
I have installed ESP-IDF (v4.3) and Eclipse (2021-03) via ESP-IDF Tools 2.9. I was doing this according to [https://github.com/espressif/idf-eclipse-plugin](https://github.com/espressif/idf-eclipse-plugin)

When I create, build and flash project by `ESP-IDF 4.3 CMD`, evereything looks fine. But when I want to do this by Eclipse all the time is the same error:

```
Building in: E:\Dawid\Programowanie\Eclipse\hello_world\build
Configuring in: E:\Dawid\Programowanie\Eclipse\hello_world\build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\esp-idf\esp-idf_v4.3\tools\cmake\toolchain-esp32.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCCACHE_ENABLE=1 -DIDF_TARGET=esp32 E:\Dawid\Programowanie\Eclipse\hello_world
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.30.1.windows.1") 
-- ccache will be used for faster recompilation
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/Dawid/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/Dawid/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/Dawid/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/Dawid/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Users/Dawid/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
-- Checking Python dependencies...
CMake Error at C:/esp-idf/esp-idf_v4.3/tools/cmake/build.cmake:274 (message):
  Some Python dependencies must be installed.  Check above message for
  details.
Call Stack (most recent call first):
  C:/esp-idf/esp-idf_v4.3/tools/cmake/build.cmake:400 (__build_check_python)
  C:/esp-idf/esp-idf_v4.3/tools/cmake/project.cmake:396 (idf_build_process)
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "E:/Dawid/Programowanie/Eclipse/hello_world/build/CMakeFiles/CMakeOutput.log".
cmake --build . -- -v
ninja: error: loading 'build.ninja': The specified file could not be found.

Build complete (0 errors, 0 warnings): E:\Dawid\Programowanie\Eclipse\hello_world\build
Total time taken to build the project: 7 834 ms
```

I attached also CMakeOutput.log 
[CMakeOutput.log](https://github.com/espressif/idf-eclipse-plugin/files/6880909/CMakeOutput.log)

**Expected behavior**
Build the example project from templates: "Hello_world" without errors.

**Environment Information:** 
[Environment Information.txt](https://github.com/espressif/idf-eclipse-plugin/files/6880875/Environment.Information.txt)

**ESP-IDF Tools Information:**
```
Executing C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts\python.exe C:\esp-idf\esp-idf_v4.3\tools\idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* xtensa-esp32s3-elf: Toolchain for Xtensa (ESP32-S3) based on GCC
  - esp-2020r3-8.4.0 (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - 1.24.0.123_64eb9ff-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20210401 (recommended, installed)
* ninja: Ninja build system
  - 1.10.2 (recommended, installed)
* idf-exe: IDF wrapper tool for Windows
  - 1.0.1 (recommended, installed)
* ccache: Ccache (compiler cache)
  - 3.7 (recommended, installed)
* dfu-util: dfu-util (Device Firmware Upgrade Utilities)
  - 0.9 (recommended, installed)
* idf-python: Embeddable Python distribution (optional)
  - 3.9.1 (recommended, installed)
* idf-python-wheels: Python Wheels distribution bundled for the specific version of IDF and Python
  - idf4.3_py3.9_2021-01-07 (recommended, installed)
```

**IDF Eclipse Plugin Version:** 
v2.1.0.202104161244

**Eclipse Error log:** 
[errorLog.log](https://github.com/espressif/idf-eclipse-plugin/files/6880874/errorLog.log)

**Tools Installer**
Here is my ESP-IDF Tools directory:
ESP-IDF Directory: C:\esp-idf\esp-idf_v4.3\
Git Exectuable Location: C:\Program Files\Git\bin\git.exe
Python Exectuable Location: C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts\python.exe

And here is the log after ESP-IDF Tools Manager->Install Tools

```
Installing tools...
This can take a while. Please be patient.
Executing C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts\python.exe C:\esp-idf\esp-idf_v4.3\tools\idf_tools.py install all
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, openocd-esp32, ninja, idf-exe, ccache, dfu-util, idf-python, idf-python-wheels
Skipping xtensa-esp32-elf@esp-2020r3-8.4.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2020r3-8.4.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2020r3-8.4.0 (already installed)
Skipping riscv32-esp-elf@1.24.0.123_64eb9ff-8.4.0 (already installed)
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping cmake@3.16.4 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20210401 (already installed)
Skipping ninja@1.10.2 (already installed)
Skipping idf-exe@1.0.1 (already installed)
Skipping ccache@3.7 (already installed)
Skipping dfu-util@0.9 (already installed)
Skipping idf-python@3.9.1 (already installed)
Skipping idf-python-wheels@idf4.3_py3.9_2021-01-07 (already installed)

Executing C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts\python.exe C:\esp-idf\esp-idf_v4.3\tools\idf_tools.py install-python-env
Python 3.9.1
pip 21.2.1 from C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages\pip (python 3.9)

Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Looking in links: c:\Users\Dawid\.espressif\tools\idf-python-wheels\idf4.3_py3.9_2021-01-07
Processing c:\esp-idf\esp-idf_v4.3\tools\kconfig_new\esp-windows-curses
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: setuptools>=21 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 4)) (51.0.0)
Requirement already satisfied: click>=7.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 8)) (7.1.2)
Requirement already satisfied: pyserial>=3.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 9)) (3.5)
Requirement already satisfied: future>=0.15.2 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 10)) (0.18.2)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 11)) (3.4.7)
Requirement already satisfied: pyparsing<2.4.0,>=2.0.3 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 12)) (2.3.1)
Requirement already satisfied: pyelftools>=0.22 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 13)) (0.27)
Requirement already satisfied: gdbgui==0.13.2.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (0.13.2.0)
Requirement already satisfied: pygdbmi<=0.9.0.2 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 18)) (0.9.0.2)
Requirement already satisfied: python-socketio<5 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 21)) (4.6.1)
Requirement already satisfied: kconfiglib==13.7.1 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 23)) (13.7.1)
Requirement already satisfied: reedsolo<=1.5.4,>=1.5.3 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 26)) (1.5.4)
Requirement already satisfied: bitstring>=3.1.6 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 27)) (3.1.9)
Requirement already satisfied: ecdsa>=0.16.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 28)) (0.17.0)
Requirement already satisfied: construct==2.10.54 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from -r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 32)) (2.10.54)
Requirement already satisfied: gevent<2.0,>=1.2.2 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (1.5.0)
Requirement already satisfied: Flask-SocketIO<3.0,>=2.9 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (2.9.6)
Requirement already satisfied: Pygments<3.0,>=2.2.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (2.9.0)
Requirement already satisfied: Flask<1.0,>=0.12.2 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (0.12.5)
Requirement already satisfied: Flask-Compress<2.0,>=1.4.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (1.10.1)
Requirement already satisfied: cffi>=1.12 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from cryptography>=2.1.4->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 11)) (1.14.6)
Requirement already satisfied: python-engineio<4,>=3.13.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from python-socketio<5->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 21)) (3.14.2)
Requirement already satisfied: six>=1.9.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from python-socketio<5->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 21)) (1.16.0)
Requirement already satisfied: windows-curses in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from esp-windows-curses==0.1->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 38)) (2.2.0)
Requirement already satisfied: pycparser in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from cffi>=1.12->cryptography>=2.1.4->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 11)) (2.20)
Requirement already satisfied: Jinja2>=2.4 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from Flask<1.0,>=0.12.2->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (3.0.1)
Requirement already satisfied: itsdangerous>=0.21 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from Flask<1.0,>=0.12.2->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (2.0.1)
Requirement already satisfied: Werkzeug<1.0,>=0.7 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from Flask<1.0,>=0.12.2->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (0.16.1)
Requirement already satisfied: brotli in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from Flask-Compress<2.0,>=1.4.0->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (1.0.9)
Requirement already satisfied: greenlet>=0.4.14 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from gevent<2.0,>=1.2.2->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (1.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dawid\.espressif\python_env\idf4.3_py3.9_env\lib\site-packages (from Jinja2>=2.4->Flask<1.0,>=0.12.2->gdbgui==0.13.2.0->-r C:\esp-idf\esp-idf_v4.3\requirements.txt (line 15)) (2.0.1)
Building wheels for collected packages: esp-windows-curses
  Building wheel for esp-windows-curses (setup.py): started
  Building wheel for esp-windows-curses (setup.py): finished with status 'done'
  Created wheel for esp-windows-curses: filename=esp_windows_curses-0.1-py3-none-any.whl size=1171 sha256=0ccc7dbb47040a04fc24a7745d6d1abc0b23331928fc442fc947f7fb4a6f2659
  Stored in directory: c:\users\dawid\appdata\local\pip\cache\wheels\94\ad\e8\4b2641f7da378dab169e1510606378c76a0a2c53ff7ef577e4
Successfully built esp-windows-curses
Installing collected packages: esp-windows-curses
  Attempting uninstall: esp-windows-curses
    Found existing installation: esp-windows-curses 0.1
    Uninstalling esp-windows-curses-0.1:
      Successfully uninstalled esp-windows-curses-0.1
Successfully installed esp-windows-curses-0.1
Installing Python packages from C:\esp-idf\esp-idf_v4.3\requirements.txt

Executing C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts\python.exe C:\esp-idf\esp-idf_v4.3\tools\idf_tools.py export --format=key-value
OPENOCD_SCRIPTS=C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210401\openocd-esp32\share\openocd\scripts
IDF_CCACHE_ENABLE=1
IDF_PYTHON_ENV_PATH=C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env
PATH=C:\Users\Dawid\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin;C:\Users\Dawid\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\Dawid\.espressif\tools\xtensa-esp32s3-elf\esp-2020r3-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\Dawid\.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\bin;C:\Users\Dawid\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\Dawid\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\Dawid\.espressif\tools\cmake\3.16.4\bin;C:\Users\Dawid\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210401\openocd-esp32\bin;C:\Users\Dawid\.espressif\tools\ninja\1.10.2\;C:\Users\Dawid\.espressif\tools\idf-exe\1.0.1\;C:\Users\Dawid\.espressif\tools\ccache\3.7\;C:\Users\Dawid\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\Users\Dawid\.espressif\python_env\idf4.3_py3.9_env\Scripts;C:\esp-idf\esp-idf_v4.3\tools;%PATH%
Configured CDT Build Environment variables. You can check Preferences > C/C++ > Build > Environment
Configured CMake toolchain. You can check Preferences > C/C++ > CMake
Install tools completed.
```

**Comment by franz-ms-muc** [comment]
have exactly the same Problem: 

Building in: C:\git\hr\CTIS2\HR-Agrar-ISO-OS\build
Configuring in: C:\git\hr\CTIS2\HR-Agrar-ISO-OS\build
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\Users\FranzHoepfinger\esp-idf-v4.3\tools\cmake\toolchain-esp32.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCCACHE_ENABLE=1 -DIDF_TARGET=esp32 C:\git\hr\CTIS2\HR-Agrar-ISO-OS
-- Found Git: C:/Users/FranzHoepfinger/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1") 
-- ccache will be used for faster recompilation
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/FranzHoepfinger/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/FranzHoepfinger/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/FranzHoepfinger/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/FranzHoepfinger/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Users/FranzHoepfinger/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Checking Python dependencies...
The following Python requirements are not satisfied:
click>=7.0
pyserial>=3.0
future>=0.15.2
cryptography>=2.1.4
pyparsing>=2.0.3,<2.4.0
pyelftools>=0.22
gdbgui==0.13.2.0
pygdbmi<=0.9.0.2
python-socketio<5
kconfiglib==13.7.1
reedsolo>=1.5.3,<=1.5.4
bitstring>=3.1.6
ecdsa>=0.16.0
construct==2.10.54
esp-windows-curses; sys_platform == 'win32'
To install the missing packages, please run "C:\Users\FranzHoepfinger\esp-idf-v4.3\install.bat"
Diagnostic information:
    IDF_PYTHON_ENV_PATH: C:\Users\FranzHoepfinger\.espressif\python_env\idf4.3_py3.8_env
    Python interpreter used: C:\Users\FranzHoepfinger\.espressif\tools\idf-python\3.8.7\python.exe
    Warning: python interpreter not running from IDF_PYTHON_ENV_PATH
    PATH: C:\Users\FranzHoepfinger\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin;C:\Users\FranzHoepfinger\.espressif\tools\xtensa-esp32s2-elf\esp-2020r3-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\FranzHoepfinger\.espressif\tools\xtensa-esp32s3-elf\esp-2020r3-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\FranzHoepfinger\.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\bin;C:\Users\FranzHoepfinger\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\FranzHoepfinger\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\FranzHoepfinger\.espressif\tools\cmake\3.16.4\bin;C:\Users\FranzHoepfinger\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210401\openocd-esp32\bin;C:\Users\FranzHoepfinger\.espressif\tools\ninja\1.10.2\;C:\Users\FranzHoepfinger\.espressif\tools\idf-exe\1.0.1\;C:\Users\FranzHoepfinger\.espressif\tools\ccache\3.7\;C:\Users\FranzHoepfinger\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\Users\FranzHoepfinger\esp-idf-v4.3\tools;C:/Users/FranzHoepfinger/.espressif/tools/idf-eclipse/2021-07//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_16.0.1.v20210528-1205/jre/bin/server;C:/Users/FranzHoepfinger/.espressif/tools/idf-eclipse/2021-07//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_16.0.1.v20210528-1205/jre/bin;C:\Users\FranzHoepfinger\.espressif\tools\idf-python\3.8.7\;C:\Users\FranzHoepfinger\.espressif\tools\idf-git\2.30.1\cmd\;C:\Program Files\Google\Chrome\Application;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Crucial\Crucial Storage Executive;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\FranzHoepfinger\.espressif\tools\idf-git\2.30.1\cmd;C:\Program Files\nodejs\;C:\Program Files\Google\Google Apps Sync\;C:\Program Files\Google\Google Apps Migration\;C:\Tools\PoolValidationTool;C:\Users\FranzHoepfinger\.espressif\python_env\idf4.3_py3.8_env\Scripts;C:\Users\FranzHoepfinger\AppData\Local\Microsoft\WindowsApps;C:\Users\FranzHoepfinger\AppData\Roaming\npm;C:\Users\FranzHoepfinger\AppData\Local\gitkraken\bin;C:\Infineon\Toolbox Launcher;C:\Infineon\LauncherService;C:\Users\FranzHoepfinger\esp-idf-v4.3
CMake Error at C:/Users/FranzHoepfinger/esp-idf-v4.3/tools/cmake/build.cmake:274 (message):
  Some Python dependencies must be installed.  Check above message for
  details.
Call Stack (most recent call first):
  C:/Users/FranzHoepfinger/esp-idf-v4.3/tools/cmake/build.cmake:400 (__build_check_python)
  C:/Users/FranzHoepfinger/esp-idf-v4.3/tools/cmake/project.cmake:396 (idf_build_process)
  CMakeLists.txt:10 (project)


-- Configuring incomplete, errors occurred!
See also "C:/git/hr/CTIS2/HR-Agrar-ISO-OS/build/CMakeFiles/CMakeOutput.log".
cmake --build . -- -v
ninja: error: loading 'build.ninja': Das System kann die angegebene Datei nicht finden.


Build complete (0 errors, 0 warnings): C:\git\hr\CTIS2\HR-Agrar-ISO-OS\build
Total time taken to build the project: 3.605 ms

**Comment by franz-ms-muc** [comment]
this seems curious: 

Diagnostic information:
    IDF_PYTHON_ENV_PATH: C:\Users\FranzHoepfinger\.espressif\python_env\idf4.3_py3.8_env
    Python interpreter used: C:\Users\FranzHoepfinger\.espressif\tools\idf-python\3.8.7\python.exe
    Warning: python interpreter not running from IDF_PYTHON_ENV_PATH

**Comment by franz-ms-muc** [comment]
idf.py build works FINE from the Console.

**Comment by franz-ms-muc** [comment]
another thing: 

if 1 time built from Console `idf.py build`

then it works to build from Eclipse. 

Operating System: windows 10  
Java Runtime Version: 16.0.1+9-24  
Eclipse Version: 4.20.0.v20210611-1600  
Eclipse CDT Version: 10.3.0.202104042017  
IDF Eclipse Plugin Version: 2.2.0.202108110455

**Comment by franz-ms-muc** [comment]
does this help anything: 

Python declared in PATH variable: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by franz-ms-muc** [comment]
it is solved with Release IDF Eclipse Plugin Version: 2.2.0.202108110455

**Comment by sigmaaa** [comment]
Hi @franz-ms-muc, @Dejwuch 
thanks for reporting the problem. I can also confirm, that I wasn't able to reproduce the problem on the latest released version. I'm closing the issue for now. Feel free to re-open if you will face this problem again. Thanks

**Comment by dizcza** [comment]
I do face the same issue with the latest Eclipse IDF plugin.
I've described the issue [here](https://github.com/espressif/idf-eclipse-plugin/issues/228#issuecomment-914040016).
Manual building with the command line does not help though.
