### ISSUE TITLE
Eclipse reports incorrect baudrate (IEP-508)

### ISSUE THREAD

**Issue by spl4** [espressif/idf-eclipse-plugin#339]
I was not able to program my ESP32. I got the following error

A fatal error occurred: Timed out waiting for packet headerCMake Error at run_serial_tool.cmake:50 (message):/home/spl/.espressif/python_env/idf4.3_py3.8_env/bin/python/home/spl/esp-idf/esp-idf-v4.3/components/esptool_py/esptool/esptool.py--chip esp32 failed ….

I checked with Eclipse
![image](https://user-images.githubusercontent.com/88339803/129265787-f4205352-52f4-455a-a9da-6745e6fc2b0a.png)

This page says Eclipse is using the correct speed. I searched some more and found this

Changed the default serial flash baud rate in "<esp-idf directory>\tools\idf_py_actions\serial_ext.py" :

baud_rate = {"names": ["-b", "--baud"],"help": "Baud rate.","scope": "global","envvar": "ESPBAUD","default": 460800, <------- replaced this value by 115200 solved my flashing issues from eclipse

Now hello world downloads and I can see the output on your favorite communications app.

**Comment by alirana01** [comment]
Hi @spl4 

Please see the latest release of tools and plugin to see if the issue is resolved if you are still facing it please open a new issue.

Best Regards
