### ISSUE TITLE
Hi friends  #353- in this ticket i am asking for documents .Based on this document I started implementing AWS OTA-library components to my esp-idf library. Using following steps 1.First i clone  master directry using https://github.com/espressif/esp-aws-iot after that i clone relese/beta branch using  git checkout release/beta  git submodule update --init --recursive  .Now i downloaded component but inside this components no cmake list because of no cmake list esp-idf not taken this esp-idf-iot component.So please any one give some ideas .thanks advance ,

### ISSUE THREAD

**Issue by ssravindhar** [espressif/idf-eclipse-plugin#354]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)

**ESP-IDF Tools Information:**
Help > Espressif Tools Manager > List Installed Tools

**IDF Eclipse Plugin Version:** 
Eclipse > About Eclipse > Installation Details > Installed Software > Search for "espressif"

For v1.1.0 and above: Eclipse > About Eclipse > Click on "espresif" icon

**Eclipse Error log:** 
Window > Show View > Error Log

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by ssravindhar** [comment]
![cmake issue](https://user-images.githubusercontent.com/13998476/131958999-88f06a99-f3d3-42d0-b77e-90b0d51f55c7.jpg)

**Comment by ssravindhar** [comment]
![cmd error](https://user-images.githubusercontent.com/13998476/131959287-dab226c7-d458-4f7a-8b45-badb23e5404a.jpg)
If i esp-idf i got this error

**Comment by kolipakakondal** [comment]
Hi @ssravindhar Could you please create this issue on https://github.com/espressif/esp-aws-iot repo as it's more relevant there

**Comment by ssravindhar** [comment]
OK @kolipakakondal 

I will create ....

**Comment by ssravindhar** [comment]
Hi @kolipakakondal  I created this issue in https://github.com/espressif/esp-aws-iot  .

Thanks for your support.
