### ISSUE TITLE
这个插件不支持arm64处理器进行开发？ (IEP-522)

### ISSUE THREAD

**Issue by LailuoA77** [espressif/idf-eclipse-plugin#355]
root@raspberrypi:~# /usr/bin/python /home/pi/esp/esp-idf-v4.3/tools/idf_tools.py install
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, openocd-esp32
ERROR: tool xtensa-esp32-elf does not have versions compatible with platform linux-arm64

**Comment by LailuoA77** [comment]
<img width="1208" alt="图片" src="https://user-images.githubusercontent.com/22634325/132004991-61d72124-6742-4bd3-be45-7359d3c73dd7.png">

**Comment by kolipakakondal** [comment]
Hello @LailuoA77 

Your platform linux-arm64 is not supported. Kindly check this https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-tools.html#list-of-idf-tools

**Comment by kolipakakondal** [comment]
Hello,

Please track https://github.com/espressif/esp-idf/issues/6432 to get the latest update on the aarch64 support. I am closing this issue as this is not specific to the eclipse plugin.

Thank you
