### ISSUE TITLE
Openocd times out when debugging large applications due to long upload times. (IEP-552)

### ISSUE THREAD

**Issue by ShenRen** [espressif/idf-eclipse-plugin#384]
我使用的是Windows10操作系统，esp-idf版本是v4.3.1，esp-idf-plugin 版本是v2.2.0, eclipse 版本是2021/06, 使用的调试工具是ESP-Prog，模块是ESP32。

我可以正常的编译, 上载和调试小尺寸的程序，但是程序文件超过1MB后就会在调试时触发openocd超时错误，让我的调试工作无法继续。

I use windows10 operating system, esp-idf version is v4.3.1, esp-idf-plugin version is v2.2.0 , eclipse version is 2021/06. The debugging tool is ESP-Prog and the module is ESP32.

I can compile, upload, and debug small programs normally, but when the program file exceeds 1MB, the OpenOCD timeout error will be triggered during debugging and my debugging work will not continue.

See the screenshot for the specific error：
![OpenOCD_TIMEOUT](https://user-images.githubusercontent.com/6782951/139022082-f32f14c7-cc28-43dd-a987-d78ecb73720a.png)

Detailed debug configuration：
![Debug_Configuration](https://user-images.githubusercontent.com/6782951/139022545-47e7e827-772f-4dd8-a058-0b53d69350ac.png)

Program size analysis:
![Program_size_analysis](https://user-images.githubusercontent.com/6782951/139022680-96ce23e0-316c-42d3-9c44-c6c9b5d4b002.png)

I would like the ESP-IDF-plugin to extend the timeout period.  In addition, the debugging interface provides options to control whether to download the program before debugging.Frequent debugging and downloading of the same application can waste a lot of time. #384

**Comment by alirana01** [comment]
@ShenRen can you provide the project that you are working with?

**Comment by kolipakakondal** [comment]
Also, verify if you've enabled verbose output using the `-d3 l oocd.log flag` in the command arguments, it seems to be this is causing an issue. Please remove this and see if that helps.

**Comment by ShenRen** [comment]
> 
I have provided you the log you need before, please check the history .

**Comment by ShenRen** [comment]
> @ShenRen can you provide the project that you are working with?

This has nothing to do with my project, but the program bin file is too large, causing the download time to exceed the timeout period you set for OpenOCD.  

see 	https://github.com/eclipse-embed-cdt/eclipse-plugins/blob/c57bac116b482ee102ebbeb875efdaea1cf25b32/plugins/org.eclipse.embedcdt.debug.gdbjtag.qemu.core/src/org/eclipse/embedcdt/debug/gdbjtag/qemu/core/dsf/GdbServerBackend.java#L33

Please extend this timeout period。By the way, my program usually takes about 50 seconds to download, which is about 2MB。

**Comment by kolipakakondal** [comment]
Hello All,

The default timeout is increased from 15 sec to 25 sec and you should be able to configure the GDB timouet using the preference page.

> Preferences > Espressif >  GDB server launch timeout
