### ISSUE TITLE
Need option for not download the program before debugging. (IEP-553)

### ISSUE THREAD

**Issue by ShenRen** [espressif/idf-eclipse-plugin#385]
the debugging interface should provides options to control whether to download the program before debugging. Frequent debugging and downloading of the same application can waste a lot of time.

**Comment by kolipakakondal** [comment]
Hello,

This issue got addressed with https://github.com/espressif/idf-eclipse-plugin/pull/393 where the user is able to configure/select `Flash every time with application binaries`.

Please check the OpenOCD debugging startup tab page here https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/OpenOCD%20Debugging.md#startup-tab

These changes are part of the 2.4.0 release. Please get the latest changes using the update site.

Thank you
