### ISSUE TITLE
ECLIPSE + IDF installation trick? (IEP-557)

### ISSUE THREAD

**Issue by timchen8992** [espressif/idf-eclipse-plugin#391]
**Describe the bug**
I had done many times to install ECLIPSE + IDF for ESP32-PICO. 
The installation process did succeed few times, however, NOT for each time.
I am wondering if there is any specific order during the installation like, IDF -> ECLIPSE or ECLIPSE -> IDF. 
In fact, I remember when it succeeded, it is ECLIPSE -> IDF and at the very last stage of IDF, we just need to 'check' the ECLIPSE environment creation...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)

**ESP-IDF Tools Information:**
Help > Espressif Tools Manager > List Installed Tools

**IDF Eclipse Plugin Version:** 
Eclipse > About Eclipse > Installation Details > Installed Software > Search for "espressif"

For v1.1.0 and above: Eclipse > About Eclipse > Click on "espresif" icon

**Eclipse Error log:** 
Window > Show View > Error Log

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by kolipakakondal** [comment]
Hello,

To improve the user experience and onboarding workflow we have also built `Espressif IDE Installer for Windows OS`. Please take a look at this https://dl.espressif.com/dl/esp-idf/

Espressif IDE details are provided [here](https://github.com/espressif/idf-eclipse-plugin/blob/master/docs/EspressifIDE.md)

These are part of the IEP v2.4.0/2.4.1 release. 

I am closing the ticket for now but if you see any further issues please open a new ticket with all the details.
