### ISSUE TITLE
Plugin Build Instructions (IEP-561)

### ISSUE THREAD

**Issue by AristarchosOfSamos** [espressif/idf-eclipse-plugin#395]
Can you have please add a section in the first repository page README.md with instructions on how to build the idf eclipse plugin itself?
It will be helpful for those that want to have the latest fixes.
Also, there is quite a long period  since August that has not been any new release but many fixes/commits that are really useful and needed. Up until August, there were releases once or twice every month, now in November, after three months there is no new release but many fixes/commits are accumulated.
So, please consider adding a section with build instructions and making a new release.

**Comment by kolipakakondal** [comment]
Hello @AristarchosOfSamos 

Please check [this]( https://github.com/espressif/idf-eclipse-plugin#how-to-build-locally) to build locally and update the plugin

You could also get the latest development update site archive from the last commit we have made.

1. Go to https://github.com/espressif/idf-eclipse-plugin/commits/master
2. Click on a green tick mark
3. Click on details
4. Click on the summary on the left
5. Scroll down to see the artifacts
6. Download `com.espressif.idf.update` and install as per the instructions mentioned here https://github.com/espressif/idf-eclipse-plugin#installPluginsUsingLocalFile

<img width="1231" alt="Screenshot 2021-11-09 at 1 23 00 PM" src="https://user-images.githubusercontent.com/8463287/140884442-af7e1ed7-8a78-41cf-9fba-0083e02ca0c9.png">

Here is the last dev build for your reference
https://github.com/espressif/idf-eclipse-plugin/suites/4227046727/artifacts/109383177
