### ISSUE TITLE
icon becomes ugly under hidpi fractional scaling (IEP-593)

### ISSUE THREAD

**Issue by erusyd** [espressif/idf-eclipse-plugin#414]
![image](https://user-images.githubusercontent.com/1529102/145486404-082619ad-b577-4d6e-8d30-fc00576bceac.png)
System: linux mint 20.2

**Comment by kolipakakondal** [comment]
Hi @alirana01  @sigmaaa Do you have a Linux box to verify this?

**Comment by erusyd** [comment]
My fractional scaling configurations:
(1) Display -> Settings -> turn on "Enable fractional scaling controls(experimental)"
(2) Display -> Layout -> in "User interface scale", select "Double (Hi-DPI)" -> then turn on "Fractional scaling", and select 125%

**Comment by kolipakakondal** [comment]
Thanks for the details @erusyd 

Looks like these problems are there at the eclipse level as mentioned here https://bugs.eclipse.org/bugs/show_bug.cgi?id=563923

As suggested in the bug, could try setting `-Dswt.autoScale=125` in the `eclipse.ini` file and restart your eclipse and see if that makes any difference

Please refer to the below resource to configure eclipse.ini file
https://wiki.eclipse.org/Eclipse.ini refer

**Comment by sigmaaa** [comment]
Hi @erusyd,

I was able to reproduce your issue. In my case, setting `-Dswt.autoScale=100` helped to fix it. Looks like, with this option, scaling has no impact on eclipse icons

**Comment by erusyd** [comment]
> Hi @erusyd,
> 
> I was able to reproduce your issue. In my case, setting `-Dswt.autoScale=100` helped to fix it. Looks like, with this option, scaling has no impact on eclipse icons

Verified @sigmaaa. Thank you guys!
