### ISSUE TITLE
"Git Executable Location" is required for install tools (IEP-100)

### ISSUE THREAD

**Issue by sch0bert** [espressif/idf-eclipse-plugin#42]
**Description**

I'm trying to setup my environment in Eclipse to run the Hello World project by following the steps from:

https://github.com/espressif/idf-eclipse-plugin/blob/master/README.md

But when I get to:

https://github.com/espressif/idf-eclipse-plugin/blob/master/README.md#installing-esp-idf-tools

The steps are not the same as the ones show in the latest IDF-Eclipse-Plugin. In the tutorial you can see that is only required to add the path to the IDF and now you need also to add the path for "Git Executable Location". 

**Screenshots**

**NOW**
![image](https://user-images.githubusercontent.com/26800631/71450673-af849480-272b-11ea-91f8-158c3e7e4ab5.png)

**CURRRENT TUTORIAL**
![image](https://user-images.githubusercontent.com/26800631/71450683-e5c21400-272b-11ea-92e5-1f86700e1a74.png)

**Comment by StavrosD** [comment]
Install git or Xcode.
Xcode installs Apple git.
I had Xcode installed, the Git executable location is: /usr/bin/git

**Comment by sch0bert** [comment]
Well I forgot to mentioned that I'm using Windows

**Comment by StavrosD** [comment]
Install git from the official website
https://git-scm.com/download/win

**Comment by kolipakakondal** [comment]
Git is required for "install tools" action as it's mentioned in the pre-requisites. https://github.com/espressif/idf-eclipse-plugin#installing-prerequisites

Documentation is updated now, please check this https://github.com/espressif/idf-eclipse-plugin#InstallTools

Thanks for reporting.
