### ISSUE TITLE
Menu "Install ESP-IDF Components" does not exist (IEP-599)

### ISSUE THREAD

**Issue by Bardi45** [espressif/idf-eclipse-plugin#420]
Hi, 

I used ESP-IDF Tools Offline Installer for Windows version 2.12. After installation and successfully compiling a project, right clicking on the project from project explorer dose not show "Install ESP-IDF Components" item. FYI, the other two options "Application Size Snalysis" and "Python Clean" are available.

Your help to fix the isssue is appreciated.

Regards,

**Comment by kolipakakondal** [comment]
Hello @Bardi45 

`Install ESP-IDF Components` is not released yet. It's currently part of the master branch.

**Comment by Bardi45** [comment]
> 
Thanks for your reply,

I thought HELP page is for the released version.
