### ISSUE TITLE
Error while compiling ESP-AWS-IoT example using eclipse idf plugin (IEP-618)

### ISSUE THREAD

**Issue by dpatil89** [espressif/idf-eclipse-plugin#437]
I am trying to compile sample application provided by esp-aws-iot (https://github.com/espressif/esp-aws-iot).
I follow steps mentioned in https://my-esp-idf.readthedocs.io/en/latest/get-started/eclipse-setup-windows.html#eclipse-windows-setup.
but getting following error.
**python "C:\\Users\\Dhananjay\\Desktop\\esp-idf-2/tools/windows/eclipse_make.py" all**
**File "C:\Users\Dhananjay\Desktop\esp-idf-2/tools/windows/eclipse_make.py", line 35, in main
    print("Running make in '%s'" % check_path(os.getcwd()))
  File "C:\Users\Dhananjay\Desktop\esp-idf-2/tools/windows/eclipse_make.py", line 24, in check_path
    winpath = subprocess.check_output(['cygpath', '-w', path]).decode('utf-8').strip()** 

Guide me to resolve this issue

**Comment by alirana01** [comment]
Hi
At the moment we are only supporting CMake.
