### ISSUE TITLE
<Erease flash> can't change window size (IEP-627)

### ISSUE THREAD

**Issue by gaupen1186** [espressif/idf-eclipse-plugin#451]
**Describe the bug**
this window can't change size, and the details can't show completely.
release v2.3.0, eclipse v 2021-09, windows 10.

![image](https://user-images.githubusercontent.com/6971820/150764524-5d29efc3-bf9a-41ad-b416-7a5500f96353.png)
![image](https://user-images.githubusercontent.com/6971820/150764599-86a34fcb-11f5-4ef5-9b6e-a2fc5bab44fb.png)

**Comment by kolipakakondal** [comment]
Hello All, Fix is available as part of the IEP 2.4.1 release. Please get the latest changes using the update site.
