### ISSUE TITLE
esp32c3 camera recommendations (IEP-642)

### ISSUE THREAD

**Issue by gregrasche** [espressif/idf-eclipse-plugin#479]
We are looking at usage of the esp32c3 SOC, and would like to have a fairly fast camera interface.   Let's say a camera that can take an image once per second. 

Questions:  
1) Do you have a vendor that you have worked with who has a 4 M pixel (or greater) camera that can easily interface to the ESP?
2) What ESP interface (SPI, DVP, I2S, or other) is used?
3) Do you have a SW package to manage the camera?
4) is the esp32s3 now recommended by ESP-AT software group?  We can likely use the MINI esp32s3 instead of the SOC if we can get the ESP-AT software and a camera of the quality we want..

This is the chip that has been recommended by Expressif for usage with the ESP-AT software package.  We must have SPI usage for the ESP-AT package.  

it needs to be a compressed image (ie jpg or mjpg for a series of image) and not raw.

**Comment by kolipakakondal** [comment]
Hi @gregrasche As this is not an eclipse plugin question, would you mind posting this question in [esp32 forum](https://www.esp32.com/viewforum.php?f=2) to get a better response.

**Comment by kolipakakondal** [comment]
https://www.esp32.com/viewtopic.php?f=2&t=26067
