### ISSUE TITLE
Serial Terminal is unavailable in the new Espressif IDE (IEP-652)

### ISSUE THREAD

**Issue by tsctrl** [espressif/idf-eclipse-plugin#492]
i was unable to see the Serial Terminal in the new IDE for v4.4 as below:
this is required to see the logs that was run on different Baud rate.

Eclipse Version: 2021-03 (4.19.0)
![image](https://user-images.githubusercontent.com/75555993/154849058-a95c3196-476c-4f81-915d-fae35b698d55.png)

New terminal Espressif IDE Version: 2.4.0
Build id: 20220128-0745:
![image](https://user-images.githubusercontent.com/75555993/154849037-75b0c120-659c-48c0-9b14-344686de0c44.png)

please help.
thanks!

**Comment by sigmaaa** [comment]
Hi @tsctrl,

this serial terminal is part of the eclipse CDT. You can install it from Espressif IDE. To do it:
* In Espressif IDE click on Help -> Install New Software -> Work with: https://download.eclipse.org/tools/cdt/releases/10.4 -> Select Terminal Features -> Install -> Restart IDE
![image](https://user-images.githubusercontent.com/24419842/154851393-42488a3f-59e0-4d27-9b70-474c588d4a8f.png)

let me know if this helps. Thanks

**Comment by tsctrl** [comment]
ok, thanks for the prompt reply. close as resolved
