### ISSUE TITLE
Unable to get sdkconfig using demo examples on eclipse (IEP-657)

### ISSUE THREAD

**Issue by Rp777** [espressif/idf-eclipse-plugin#497]
Hi,

Eclipse version: 4.22
IDF Version: ESP-IDF v4.4
Hardware: ESP32
Have followed the installation instructions from: https://github.com/espressif/idf-eclipse-plugin/

I am trying to run demo example for mqtt ssl with mutual auth.
But i am unable to do the configuration of the project sdkconfig file is missing

Tried running hello word example it works for me.
Attached is the screen shot of the project .
Can any one give me any pointers on this? 
I am new to this.
Am I missing any other configurations/installations?

Thanks in advance
![error_eclipse](https://user-images.githubusercontent.com/36836413/156002258-2e6def7a-f4fe-47c4-9df6-b89019cc18cf.png)

**Comment by kolipakakondal** [comment]
Hello @Rp777 

sdkconfig file will be available only after the build. Looking at the screenshot and errors project is not built yet. Could you check after the build?
