### ISSUE TITLE
Clean up Launch Target (IEP-659)

### ISSUE THREAD

**Issue by tsctrl** [espressif/idf-eclipse-plugin#500]
how do i clean up the list? it look messy

![image](https://user-images.githubusercontent.com/75555993/156886843-06555d14-d55c-486e-b654-8a823d17e394.png)

thank you

**Comment by sigmaaa** [comment]
Hi @tsctrl,

sorry for the late reply. To delete the launch target, you need to select it and click on the wheel on the launch bar 
![image](https://user-images.githubusercontent.com/24419842/158153355-ad03c23c-9ad1-4e46-bec6-91f21be968bb.png)

then click on delete button 
![image](https://user-images.githubusercontent.com/24419842/158153654-fa5c25cc-2ac4-4a7a-adf7-5b8845ad0405.png)

**Comment by tsctrl** [comment]
ok, thank you. i didnt aware of the delete button
