### ISSUE TITLE
Environment variables defined in Preferences -> C++ -> Build -> Environment are prepended with "null:" when used in a CMakeList.txt (IEP-702)

### ISSUE THREAD

**Issue by expresspotato** [espressif/idf-eclipse-plugin#535]
**Describe the bug**
The environment variable value used in a CMakeLists.txt appears to be prepended with **null:** which causes the build to fail. 

**To Reproduce**
1. Include an environment variable in global C++ -> Build -> Environment
2. Example: "ADF_PATH" with a value of "/Users/kevin/esp/esp-adf"

**Expected behavior**
The value should be as presented

**Screenshots**
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/4267949/169191807-707c8f94-0d88-4fd7-b35a-fb140742bae7.png">

**IDF Eclipse Plugin Version:** 
v2.4.2

**Comment by kolipakakondal** [comment]
Hi @expresspotato 
Seems to be this is a bug from Eclipse CDT. As a workaround, you could Click on `Edit` and click Ok without modifying anything. This should work.
