### ISSUE TITLE
Not using virtualenv (IEP-137)

### ISSUE THREAD

**Issue by veerendra-nath** [espressif/idf-eclipse-plugin#55]
i installed and set up plugin , 
i created the first project , the build using the python virtual environment at this time 
i created 2nd project this time its not using virtual environment, build is not working because pyparsing in system python module is newer than the requirements , i am using arch linux

**Comment by kolipakakondal** [comment]
Hi, Thanks for reporting the issue. Build will use the python path from the CDT build preferences. Can 
you verify the python path environment variable - IDF_PYTHON_ENV_PATH
(Preferences > C/C++ > Build >Environment)

Is the same python used during compiling the project?

**Comment by veerendra-nath** [comment]
Hi, thanks fro responding ,
now the error not occurred(IN old(beta) and new (rc)version of plugin ) , IDF_PYTHON_ENV_PATH variable is set to idf virtual env folder ,
will report if  it occurred again
