### ISSUE TITLE
esp32c3 toolchain does not show up in configuration window (IEP-717)

### ISSUE THREAD

**Issue by pn21** [espressif/idf-eclipse-plugin#551]
I am trying to create a new project on my work laptop which uses esp32c3-mini. I have installed everything as shown in the below pictures (starting from “build environment”) however as shown (highlighted in red filename: "Configuration.jpg") below I do not get the option of selecting the esp32c3 toolchain. I have also “added” the target as esp32c3 (did not show by default, only showed esp32 and esp32s2. Since the below toolchain setting is wrong my code does not compile correctly. What do I need to do to get it working?
I am using esp-idf 4.3.1

Thanks
Pankaj

![BuildEnvironment](https://user-images.githubusercontent.com/79219781/174795709-bdc6ba4f-85c5-4472-a0c7-d25f9153549b.JPG)
![ConfigurationWindow](https://user-images.githubusercontent.com/79219781/174795710-e2bb604f-9f9f-4bb1-b936-7af0af8c65b0.jpg)
![OfficeCmake](https://user-images.githubusercontent.com/79219781/174795712-c176456f-0cff-492c-a0e0-272c5e0ba92e.jpg)
![OfficeCoreBuildToolchain](https://user-images.githubusercontent.com/79219781/174795716-0bc76c9f-58c3-49fc-80bf-408deaa0f0a3.jpg)

**Comment by kolipakakondal** [comment]
Hi @pn21 

Could you verify the launch target you've created for `esp32c3` in the `New ESP Target` dialog?
 
<img width="581" alt="Screenshot 2022-06-21 at 7 08 05 PM" src="https://user-images.githubusercontent.com/8463287/174815270-bbf3d690-8690-4d77-907a-8c06474034e2.png">


<img width="842" alt="Screenshot 2022-06-21 at 7 07 52 PM" src="https://user-images.githubusercontent.com/8463287/174815291-52602b0e-44d1-40bb-95e1-e3e4c3bcd3c5.png">

**Comment by kolipakakondal** [comment]
Hello, Closing this issue as there is no response. Feel free to report us back if you still have a problem. Thanks
