### ISSUE TITLE
A target flash problem (IEP-140)

### ISSUE THREAD

**Issue by jenya7** [espressif/idf-eclipse-plugin#58]
I open a new Espressif IDF project as a template. It compiles OK. Then I connect my ESP32 board and see it in Device Manager. When I press Run button to flash the board I get an error

> Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'door_beacon'.
java.lang.NullPointerException 

How do I configure the project to flash on my dev board?

**Comment by kolipakakondal** [comment]
Thanks for reporting the issue. Could you please share with me an error log?
https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by kolipakakondal** [comment]
Can you please try with the latest build?

**Comment by jenya7** [comment]
Thank you. I'll try.

**Comment by kolipakakondal** [comment]
Closing the issue as it's not producible with the latest release. We also have a latest release v1.0.1, please update to the latest and let us know if you see any issue
