### ISSUE TITLE
How to use idf.py menuconfig from Eclipse IDE (IEP-761)

### ISSUE THREAD

**Issue by PriyadharshiniMohan** [espressif/idf-eclipse-plugin#595]
Hi
I am using Eclipse IDE with ESP IDF plugin. I have started using it and ran through few examples also.
For setting target, I am not using **idf.py set-target** command, since it is available in the Eclipse toolbar.
Similarly do we have an option in Eclipse for **idf.py menuconfig** command. If not, how to use it from Eclipse IDE?

Thanks
Priya

**Comment by sigmaaa** [comment]
Hi @PriyadharshiniMohan,

for `idf.py menuconfig` you can use SDK config configuration editor. Please, check this [link](https://github.com/espressif/idf-eclipse-plugin#sdk-configuration-editor). Thanks
