### ISSUE TITLE
Unresolved includes in latest idf-eclipse-plugin in Debug Launch mode (IEP-142)

### ISSUE THREAD

**Issue by mvgorban** [espressif/idf-eclipse-plugin#60]
Hi! 
I use  Windows10-1809/CDT Version: 2019-12 (4.14.0)/Build id: 20191212-1212/ Espressif IDF Plugins for Eclipse 1.0.0.202002201116 (updated to latest BETA 5 com.espressif.idf.update-v999-71-g9550085e that should fix the includes issue, as discussed before in https://github.com/espressif/idf-eclipse-plugin/issues/43#).

1) Using last plugin version In RUN launch mode all is OK **after building**, So, Indexer knows about includes only after build. OK.
2) In Debug Launch mode the including issue is permanent. No ways here to say Indexer about required path to IDF components... "Source" tab in GDB Hardware Debugging configuration cannot to help unfortunatly... or can?
So, how I could to fix this issue in Debug mode? Is it possible? Thanks!
![1](https://user-images.githubusercontent.com/23656658/75458082-f5591580-5985-11ea-8cef-c08421b71f40.gif)

![2](https://user-images.githubusercontent.com/23656658/75458092-fa1dc980-5985-11ea-82f4-ac5c247cfb79.gif)

![3](https://user-images.githubusercontent.com/23656658/75458111-0144d780-5986-11ea-9356-bcb6d918e444.gif)

**Comment by mvgorban** [comment]
I have checked Indexer log file, no any component pathes (-I option) in Debug mode (in Run mode all is OK, components PATH added **after build only**).
As I understand, in Run mode, if target esp32 is selected, the plugin provides info for Indexer properly, but only after building. But in Debug mode Indexer is not notified. Why? What did I wrong? May be its happened because there is not any Target is selected in Debug mode? But I cannot to select esp32 target even  it created before,  this new target is just not present in selection...  

[dbg_DEBUG_MODE_AFTER_BUILD.log](https://github.com/espressif/idf-eclipse-plugin/files/4262901/dbg_DEBUG_MODE_AFTER_BUILD.log)
[dbg_DEBUG_MODE_BEFORE_BUILD.log](https://github.com/espressif/idf-eclipse-plugin/files/4262902/dbg_DEBUG_MODE_BEFORE_BUILD.log)
[dbg_RUN_MODE_AFTER_BUILD.log](https://github.com/espressif/idf-eclipse-plugin/files/4262903/dbg_RUN_MODE_AFTER_BUILD.log)
[dbg_RUN_MODE_BEFORE_BUILD.log](https://github.com/espressif/idf-eclipse-plugin/files/4262904/dbg_RUN_MODE_BEFORE_BUILD.log)

**Comment by kolipakakondal** [comment]
I'm able to reproduce the issue in the debug mode. As a workaround, when you move to 'C/C++' perspective run mode, do the re-build of the project using 'Project >C/C++ Index >Rebuild' that should resolve the issue.

We will update you once the issue is resolved. Thanks for reporting.

**Comment by kolipakakondal** [comment]
When you move back to the run mode,  just clicking on the build icon also resolves the issue.

**Comment by kolipakakondal** [comment]
We have released 2.0.0-beta, this has a fix for unresolved includes issue, please get the latest changes using https://dl.espressif.com/dl/idf-eclipse-plugin/updates/beta/ update site

**Comment by sigmaaa** [comment]
Indexer works better in the latest release. You also could face a problem with the indexer after changing modes from debug to launch, now it's fixed. Now it's fixed. Please, check the [2.2.0 plugin version](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.2.0) and feel free to raise an issue if you will face some problems with it
