### ISSUE TITLE
IDF Eclipse Plugin does not yet support Eclipse CDT 2022-12 (IEP-826)

### ISSUE THREAD

**Issue by Mroogal** [espressif/idf-eclipse-plugin#654]
**Describe the bug**
Hi,
I tried to build and lunch a template program on my ESP32-S3 dev-kit and problem occured. It has a problem with building and shows error:

Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project 'blink'.
'int com.espressif.idf.core.build.IDFBuildConfiguration.watchProcess(java.lang.Process, org.eclipse.cdt.core.resources.IConsole)'

I tried to follow the tutorial from: [https://github.com/espressif/idf-eclipse-plugin#cmakeproject](https://github.com/espressif/idf-eclipse-plugin#cmakeproject) to setup IDE but maybe I lost some steps in-between while configuring a workplace.

**To Reproduce**
1. Build template program.

**Expected behavior**
Expected behaviour is being able to build project properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/26607006/206879184-6f656593-42a8-43cd-8b6c-8aa950e34556.png)

**Eclipse Error log:** 
I attached a file with a log.
[blink_project_build_error_log.txt](https://github.com/espressif/idf-eclipse-plugin/files/10201170/blink_project_build_error_log.txt)

**Comment by kolipakakondal** [comment]
Hi @Mroogal i am sorry for the issue. Looks like you're using the latest Eclipse version `Eclipse 2022-12` which is not yet supported by the plugin. I would recommend to use the `Eclipse 2022-09` version which is more stable and support IDF Eclipse plugin

You can find 2022-09 releases here https://www.eclipse.org/downloads/packages/release/2022-09/r

Anyway thanks for reporting this issue, will look into it.

**Comment by Coffeeye** [comment]
Can confirm, latest update on 2022-12 cause error.
Rollback changes or redownload version 2022-12 seems to have no effect.
Changing to 2022-09 solves the issue.

```
Errors occurred during the build.
Errors running builder 'CDT Core Builder' on project.
'int com.espressif.idf.core.build.IDFBuildConfiguration.watchProcess(java.lang.Process, org.eclipse.cdt.core.resources.IConsole)'
```

**Comment by Mroogal** [comment]
Yeah, I changed back to 2022-09 and it worked, so the issue is with 2022-12 version of the eclipse.

**Comment by kolipakakondal** [comment]
Thanks @Mroogal @Coffeeye for verifying and updating on this.

**Comment by Nike-Prallow** [comment]
Thank you! Now version CDT 2023-03 works.

**Comment by kolipakakondal** [comment]
As [Eclipse 2022-12](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.9.1) supported is added with v2.9.1 build, hence closing this issue.
