### ISSUE TITLE
list of installed tools does not work (IEP-151)

### ISSUE THREAD

**Issue by umfundi** [espressif/idf-eclipse-plugin#66]
**Describe the bug**
As per subject. 

PYTHON path: null

but it isn't.

i have tried reinstalling Python 3.6 and python 3.8

Tools reinstalling using 3.6 and 3.8

![image](https://user-images.githubusercontent.com/2498620/77947423-cce17580-72bb-11ea-9e81-43c31c565013.png)

Why is it using a path to Visual Studio? i can't find where that environment variable is set.

**Comment by kolipakakondal** [comment]
As you raised here https://github.com/espressif/esp-idf/issues/5025#event-3182371527
This is due to the python registry entry in windows.

**Comment by kolipakakondal** [comment]
Please close the issue if it's working fine now?

**Comment by umfundi** [comment]
gave up on eclipse and moved to VisualGDB
