### ISSUE TITLE
Issues associated with creating an Espressif project in Eclipse (IEP-846)

### ISSUE THREAD

**Issue by huzzziiii** [espressif/idf-eclipse-plugin#673]
So I have the following issues:
- Upon creating an Espressif Project in Eclipse, I don't see C/C++ Build section. Why is that so?
- `IDF_PATH` and `IDF_TOOLS_PATH` are set to different paths but the eclipse seems to use a different path upon compilation. I have verified the paths by printing them in the terminal via `printenv`.
- How does one include the files (that are not `main.c`) located in esp-idf path which is seemingly set in `IDF_PATH` parameter? For instance, using `#include "esp_system.h"` in `file1.c` results in an error / doesn't recognize the path, but works fine in `main.c`.

**Comment by kolipakakondal** [comment]
Hello, A lot has changed in the idf-eclipse-plugin for last 2 years. Please try with the latest one and see if you have any reported problems.

https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.10.0


idf-eclipse-plugin doesn't use IDF_TOOLS_PATH, it will rely on IDF_PATH and PATH from the Eclipse CDT build environment variables for identifying toolchains.

Indexer probems reported in this ticket were fixed, please give a try with the latest one. Headers will be resolved only after the project build is completed.
