### ISSUE TITLE
改为中文后ide启动失败 (IEP-851)

### ISSUE THREAD

**Issue by OPEN-F** [espressif/idf-eclipse-plugin#675]
**Describe the bug**
改为中文后ide启动失败，如下图

**To Reproduce**
1. Go to 'Chinese or 中文'
2. 退出ide
3. See error

**Expected behavior**
ide不能打开，并弹出如下图报错

**Screenshots**
![image](https://user-images.githubusercontent.com/122686738/212480493-28e5c3e8-4007-4963-9242-99262700ae23.png)

**Espressif-IDE Product Information:**
2.7.0

**Eclipse Error log:** 
详情查看附件

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log 
[1673711154074.log](https://github.com/espressif/idf-eclipse-plugin/files/10418094/1673711154074.log)

**Comment by sigmaaa** [comment]
Hi @OPEN-F,

Looks like you are using java 8, but Java 11 is required. Because of Java 8 a lot of requirements are unresolved.
Download and install Java SE from [here](https://www.oracle.com/technetwork/java/javase/downloads/index.html)

**Comment by OPEN-F** [comment]
非常感谢您的帮助，但是在我安装Java11后出现了如下的问题
![屏幕截图 2023-01-17 153433](https://user-images.githubusercontent.com/122686738/212837224-3a28b94f-feed-4cf8-8b63-044c92954910.png)
![屏幕截图 2023-01-17 153453](https://user-images.githubusercontent.com/122686738/212837237-234591ad-0b8e-4dd2-ab26-c8e0e51705cb.png)
我也尝试过安装最新的java17，但依然出现了类似的问题，如下图
![屏幕截图 2023-01-17 152523](https://user-images.githubusercontent.com/122686738/212837551-f47ae315-4011-4648-bd00-4a82a74cee75.png)
![屏幕截图 2023-01-17 152547](https://user-images.githubusercontent.com/122686738/212837583-0d27b59b-5898-497e-a185-deb06928bb4c.png)

**Comment by OPEN-F** [comment]
@sigmaaa 非常感谢你的帮助，但是在我安装了Java11后（卸载了java8）,又重新安装了Espressif-IDE，出现了如下问题（前两幅图片）
![屏幕截图 2023-01-17 153433](https://user-images.githubusercontent.com/122686738/212838513-bbfe64fd-3cb8-4c03-86d1-af205af72365.png)
![屏幕截图 2023-01-17 153453](https://user-images.githubusercontent.com/122686738/212838549-cb07d740-903b-410c-8b79-9f61a3252d73.png)
我用同样的方法安装了新版的java17，也出来类似问题。（后两幅图片）
![屏幕截图 2023-01-17 152523](https://user-images.githubusercontent.com/122686738/212838570-4c51c9c2-a0f7-4da6-aaac-6b07ab3ea7fc.png)
![屏幕截图 2023-01-17 152547](https://user-images.githubusercontent.com/122686738/212838581-9b3466d4-a456-4d44-9b30-03ea13563fde.png)

**Comment by OPEN-F** [comment]
![image](https://user-images.githubusercontent.com/122686738/212849190-73abed7c-f1d2-4582-81ca-85af29acf474.png)
这是JAVA的版本号

**Comment by sigmaaa** [comment]
Hi @OPEN-F,

Maybe the problem is related to the default JVM path. Can you check your espressif-ide.ini file in the Espressif IDE folder? Try to edit it with `-vm` argument like this:
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.600.v20220720-1916
-data
@noDefault
-vm 
C:\Program Files\Java\jdk-11.0.9\bin\server\jvm.dll
-vmargs
-Xms256m
-Xmx2048m
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area.default=@user.home/espressif-workspace
```

where instead of `C:\Program Files\Java\jdk-11.0.9\bin\server\jvm.dll` should path relative to your Java folder.

**Comment by OPEN-F** [comment]
Hi @sigmaaa 
在你的帮助下，我更改了ini文件（如下）,使ide顺利启动，但是仍然不能使ide的语言更改为中文，如下图所示，这是什么原因呢？
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.600.v20220720-1916
-vm 
D:\program files\Java\jdk-11.0.15\bin\server\jvm.dll
-nl
zh
-data
@noDefault
-vmargs
-Dosgi.instance.area.default=@user.home/espressif-workspace
-Dosgi.requiredJavaVersion=11
-Xmx2048m
-Xms256m
```

**Comment by OPEN-F** [comment]
你好，我想对我们交流的问题做一个总结教程并在一些开放性平台上分享，其中可能会涉及到您告知我的解决方法，可以吗？
