### ISSUE TITLE
Update ESP-IDF removes Plugin (IEP-860)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/idf-eclipse-plugin#682]
**Describe the bug**  
Update ESP-IDE removes Plugin

**To Reproduce**  

1.  espressif-ide-setup-2.7.0-with-esp-idf-5.0.exe
2.  install normally
3.  all OK
4.  Go to "install new Software" select the Espressif Plugin, Update.
5.  Restart
6.  Espressif Plugin is missing; no "Espressif" Menu on the Top.

**Comment by sigmaaa** [comment]
Hi @franz-ms-muc,
Thank you for reporting this. Probably, during the update, the plugin dependencies like eclipse CDT also updated and the new version of dependencies requires Java 17. This might be the problem, that dependencies are not getting resolved. 

Please, attach the [error log](https://github.com/espressif/idf-eclipse-plugin#error-log) if you have one, this will help. But it's ok if you don't have it, I will try to reproduce it later today.

**Comment by franz-ms-muc** [comment]
![image](https://user-images.githubusercontent.com/69573151/215064461-3fb2ceb4-c0f3-4852-b046-41277671954e.png)

**Comment by franz-ms-muc** [comment]
![image](https://user-images.githubusercontent.com/69573151/215065228-d9d2650d-7fe4-4633-9b7d-0bdb410ce647.png)

**Comment by franz-ms-muc** [comment]
> Please, attach the [error log](https://github.com/espressif/idf-eclipse-plugin#error-log) if you have one, this will help. But it's ok if you don't have it, I will try to reproduce it later today.

The Error Log seems gone as well.

**Comment by franz-ms-muc** [comment]
if i download 
eclipse-embedcpp-2022-09-R-win32-x86_64.zip
and install the Plugin [plugin](https://github.com/espressif/idf-eclipse-plugin#installing-idf-plugin-using-update-site-url)
then it in fact show massive Information:

![image](https://user-images.githubusercontent.com/69573151/215066684-03f60665-fd14-41b5-80d3-1a156c06ad74.png)


![image](https://user-images.githubusercontent.com/69573151/215066750-558a800b-5f63-432e-ac92-be674bb8d716.png)

**Comment by franz-ms-muc** [comment]
i will try the 2nd option: 
![image](https://user-images.githubusercontent.com/69573151/215066855-d0c86127-2948-415a-b03c-148f19718a21.png)

**Comment by franz-ms-muc** [comment]
All OK on a Eclipse. 


![image](https://user-images.githubusercontent.com/69573151/215067844-efb104e0-98f7-425b-8d2c-296a4573a234.png)

**Comment by kolipakakondal** [comment]
Eclipse 2022-12 support is added with [v2.9.1](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.9.1), hence closing this issue
