### ISSUE TITLE
pls take this over also to Launch Terminal: (IEP-877)

### ISSUE THREAD

**Issue by f-hoepfinger-hr-agrartechnik** [espressif/idf-eclipse-plugin#697]
pls take this over also to 
Launch Terminal:
![image](https://user-images.githubusercontent.com/69118498/217590630-3f4cae45-4f82-4a76-9731-42eba650133c.png)

_Originally posted by @f-hoepfinger-hr-agrartechnik in https://github.com/espressif/idf-eclipse-plugin/issues/683#issuecomment-1422896116_

**Comment by kolipakakondal** [comment]
Hi @f-hoepfinger-hr-agrartechnik Could you please add more details about the bug? What is the problem and what is the expected behavior?

**Comment by f-hoepfinger-hr-agrartechnik** [comment]
ESP-IDF Serial Monitor makes only sense on ESP-IDF Projects. so other Projects should not be listed there. 

you made this already for the Top dropdown list.

**Comment by kolipakakondal** [comment]
Ok, thanks for the feedback

**Comment by kolipakakondal** [comment]
https://github.com/espressif/idf-eclipse-plugin/pull/699

**Comment by kolipakakondal** [comment]
This is fixed as part of v2.9.0 release, please check
