### ISSUE TITLE
Documentation:  idf-eclipse-plugin/README.md does not include instructions for launch bar (IEP-885)

### ISSUE THREAD

**Issue by cjearls-witekio** [espressif/idf-eclipse-plugin#701]
Issue: https://github.com/espressif/idf-eclipse-plugin#readme 
Under the header "Configuring Launch target" the instructions are incredibly vague and do not guide the user to how to enable the launch bar if it is not properly enabled. Text in question follows below.

Next, we need to tell CDT to use the toolchain for our project so that all the headers will be indexed and resolved. This is accomplished through the Launch Bar, the new widget set you see on the far left of the toolbar. 

_Maybe include an  image of the gui with the launch bar enabled here_
![image](https://user-images.githubusercontent.com/119621970/218576629-511f9d38-e8e7-4f54-86cd-ba36a3bfe4d3.png)

**Note:** This will be shown only when you have a project in the project explorer. **If the launch bar is not displayed it can be enabled by going to ```Wndow ``` > ```Preferences``` Then type in the Filter at the top left "Launch Bar" Click on Launch bar from the menu, then tick ```Enable the Launch Bar.``` This allows the launch bar to be displayed if it was not previously.**
![image](https://user-images.githubusercontent.com/119621970/218576735-9ed98ea1-27f5-42ca-a2cb-63feeb543451.png)

This way it is a bit more descriptive, as the launch bar may or may not always be present depending on a user's configuration.

**Comment by kolipakakondal** [comment]
Thanks for sharing the feedback @cjearls-witekio We will improve this

**Comment by kolipakakondal** [comment]
Added to the FAQ doc
https://github.com/espressif/idf-eclipse-plugin/blob/master/FAQ.md#how-to-enable-the-launchbar-in-espressif-ide
