### ISSUE TITLE
During building warning is printed build process hangs (IEP-909)

### ISSUE THREAD

**Issue by RuslanSpartak** [espressif/idf-eclipse-plugin#723]
**Describe the bug**
When I try to build project, and I have a warning printed in console building process is hanging. 

**To Reproduce**
1. Just add some #warning 
2. Build project

**Expected behavior**
Project build finish
**Screenshots**

**Espressif-IDE Product Information:**
Operating System: windows 11
Java Runtime Version: 19.0.2+7
Eclipse Version: 4.25.0.v20220831-1800
Eclipse CDT Version: 10.7.1.202208160035
IDF Eclipse Plugin Version: 2.9.0.202303201505
ESP-IDF v5.1-dev-4167-gab63aaa4a2-dirty
Python set for IDF_PYTHON_ENV: Python 3.9.9

**Eclipse Error log:** 
Window > Show View > Other > Search for "Error Log" (Attach as a file)

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by sigmaaa** [comment]
Hi @RuslanSpartak 
Thank you for reporting this. We have been able to reproduce this problem and we will provide you with an update as soon as possible.

**Comment by RuslanSpartak** [comment]
> 

Okay. thanks a lot.

**Comment by rapeauxa** [comment]
Can confirm this on my side as well. Recently upgraded IDF from 4.4 to 5.0.1-dirty on Eclipse 2022-09 - builds hang on printing any warning. However this issue does not occur with the same IDF version on Eclipse 2021-09 and the build then correctly finishes.

System:
Windows 10 Pro
Java Runtime Version: java 18.0.1.1 2022-04-22
Eclipse: 2022-09
Python: 3.10.4

**Comment by rbruneau-altyor** [comment]
Same problem here, is there a way to get a previous version that does not have the issue ?

**Comment by RuslanSpartak** [comment]
> Same problem here, is there a way to get a previous version that does not have the issue ?

Just take v2.8.0 of plugin - this one is working.

**Comment by kolipakakondal** [comment]
Hi All,

We have released IEP v2.9.1 with the project build hung issue, project close and reopen issues, and a few more bug fixes to improve the quality of the plugin.

please refer to the release notes 
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.9.1

Installing IDF Plugins using the Update site URL:
https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/

Installing IDF Plugins using the local archive file:
https://dl.espressif.com/dl/idf-eclipse-plugin/updates/com.espressif.idf.update-2.9.1.zip

Espressif IDE
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-macosx-cocoa-aarch64-v2.9.1.dmg
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-macosx-cocoa-x86_64-v2.9.1.dmg
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-2.9.1-win32.win32.x86_64.zip
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-2.9.1-linux.gtk.x86_64.tar.gz

**Comment by kolipakakondal** [comment]
As this is fixed, closing this issue

**Comment by GerryBriggs** [comment]
I am having the same problem now which I'd never encountered before
