### ISSUE TITLE
java.io.FileNotFoundException compile_commands.json (IEP-924)

### ISSUE THREAD

**Issue by RJSDevel** [espressif/idf-eclipse-plugin#738]
**Describe the bug**
Can't build the project

**To Reproduce**
1. Create new Zigbee project
2. Try to built it
3. Get an error

**Expected behavior**
Built an project

**Espressif-IDE Product Information:**
[info.txt](https://github.com/espressif/idf-eclipse-plugin/files/11151251/info.txt)
**Eclipse Error log:** 
[error_log.log](https://github.com/espressif/idf-eclipse-plugin/files/11151252/error_log.log)

**Comment by kolipakakondal** [comment]
Hi @RJSDevel  Sorry for the issue. Are you trying to build with a custom build directory?

**Comment by RJSDevel** [comment]
Hi, no I don't, just in workspace.
I've created the project from template zigbee_light for esp32c6

**Comment by sigmaaa** [comment]
Hi @RJSDevel,
thank you for reporting this. It's fixed now, verified on 2.11 but should be okay on the previous version as well.
