### ISSUE TITLE
Workspace hangs if project is closed while indexer is running (IEP-928)

### ISSUE THREAD

**Issue by davidlehrian** [espressif/idf-eclipse-plugin#742]
PR #729 fixed the issue I was having with closing and opening projects, but there is an issue where the workspace will hang if a project is closed while the indexer is still running. 

To recreate this:

Open a project and wait till you see the C/C++ Indexer in the status bar. If it doesn't come up right click on the project and click Index->Rebuild. 
When you see the C/C++ Indexer in the status bar right click the project and select Close Project. 

[Espressif Product Info.txt](https://github.com/espressif/idf-eclipse-plugin/files/11180801/Espressif.Product.Info.txt)

**Comment by kolipakakondal** [comment]
Fix is part of the v2.11.0 release, https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.11.0

Hence closing this issue
