### ISSUE TITLE
Launching Project Encountered Problem "Index 1 out of bound for length 1" (IEP-983)

### ISSUE THREAD

**Issue by radhikaalpha** [espressif/idf-eclipse-plugin#787]
I have installed eclipse ide. The versions of all related installed software are as follow,
                      Operating System: windows 10
            Java Runtime Version: 17.0.7+8-LTS-224
            Eclipse Version: 4.27.0.v20230302-0300
            Eclipse CDT Version: 11.1.1.202303201356
            IDF Eclipse Plugin Version: 2.10.0.202306060331

Created a project using existing example code esp_http_client for ESP32-S3-DevKitM-1.
It got built successfully. But it is giving error while flashing the code on Dev Board as 'Launching Project Encountered Problem "Index 1 out of bound for length 1"'
![image](https://github.com/espressif/idf-eclipse-plugin/assets/55236971/2b3585a3-cbfd-4821-958d-5804b647546f)

Can you please guide us for resolving this issue? Are we missing something?
For your information, we have built generic_gpio example and also flashed the same to development kit. So, development kit is working.

**Comment by kolipakakondal** [comment]
Hi @radhikaalpha It seems to be LaunchBar is missing in your eclipse cdt. Could you share how did go about installing Eclipse CDT and plugin?

Please try the following.

1. Go to `Install New Software`
2. Add this update site `https://download.eclipse.org/tools/cdt/releases/11.1`
3. Install the Launchbar plugin if it's missing. Please find the screenshot below.

<img width="923" alt="Screenshot 2023-06-19 at 10 12 35 PM" src="https://github.com/espressif/idf-eclipse-plugin/assets/8463287/9c9bfa11-601a-460c-b656-5c48a2ac259d">

if it's already installed, for some reason Launchbar is disabled, please enable it
https://github.com/espressif/idf-eclipse-plugin/blob/master/FAQ.md#how-to-enable-the-launchbar-in-espressif-ide

**Comment by radhikaalpha** [comment]
Hi, Thanks for your reply. It got resolved by enabling LaunchBar in preferences.

**Comment by kolipakakondal** [comment]
Hi @radhikaalpha Thanks for the update and glad that it's working for you. Would you mind sharing how did you install eclipse cdt and plugin? Because if someone installed Eclipse CDT 2023-03 launchbar is enabled by default so I wonder how come it was missing in your case.

**Comment by radhikaalpha** [comment]
- We have followed below links to install the IDE
            Install Java 17, Git & python from
                  https://github.com/espressif/idf-eclipse-plugin/blob/master/README.md
            For eclipse installation refer below
                  https://www.beyondlogic.org/getting-started-with-the-espressif-esp-idf-eclipse-ide/
            ESP-IDF with Eclipse
                  https://www.youtube.com/watch?v=OSm-NN97woM

**Comment by radhikaalpha** [comment]
When I installedthe IDE, The LaunchBar was there in my IDE. But I don't have any idea where and how it went later. I haven't done anything related to it (ie. haven't manually disabled it)

**Comment by kolipakakondal** [comment]
Ok, thanks for the info.
