### ISSUE TITLE
No `Eclipse Marketplace`  menu entry at Help menu (IEP-997)

### ISSUE THREAD

**Issue by tonyho** [espressif/idf-eclipse-plugin#794]
**Describe the bug**
No `Eclipse Marketplace`  menu entry at Help menu.

**Expected behavior**
Open Eclipse marketplace for user to install extensions.

**Comment by kolipakakondal** [comment]
Hi @tonyho Is this what you're looking for? It's part of every eclipse installation.

<img width="583" alt="Screenshot 2023-07-18 at 10 11 26 AM" src="https://github.com/espressif/idf-eclipse-plugin/assets/8463287/a3dd9ab8-4ae6-4918-a136-afd25b72fc63">

You can also find esp-idf eclipse plugin in the marketplace
<img width="834" alt="Screenshot 2023-07-18 at 10 14 40 AM" src="https://github.com/espressif/idf-eclipse-plugin/assets/8463287/ab1d8b50-1419-428e-a2af-3b6cc10aa01b">

**Comment by kolipakakondal** [comment]
Could you please share your environment details to check further on this

**Comment by tonyho** [comment]
> I realized it's missing in the Espressif-IDE. Here is the PR #796↳

Thanks for the fast response.  That's exactly what I mean.

**Comment by kolipakakondal** [comment]
Fix is part of the v2.11.0 release. https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.11.0

Hence closing this issue
