### ISSUE TITLE
sdkconfig.defaults do not get opened by SDK Configuration editor (Bug/Feature request) (IEP-1103)

### ISSUE THREAD

**Issue by Maksons** [espressif/idf-eclipse-plugin#844]
File "sdkconfig.defaults" should get opened by "SDK Configureation" editor same way as "sdkconfig" file.

Espressif-IDE on Linux
Version: 2.11.1
Build id: 20231027-0959

**Comment by alirana01** [comment]
Fixed with last release

**Comment by emaayan** [comment]
> Fixed with last release

hi i have version 3.0.0 and it's still happening.
