### ISSUE TITLE
Attempted to upgrade the plugin, and it completely uninstalled itself (IEP-1113)

### ISSUE THREAD

**Issue by mbratch** [espressif/idf-eclipse-plugin#855]
**Describe the bug**
I was running an older Espressif plugin. I executed Help > Check for Updates, then selected only the Espressif plugin to upgrade it.

After the update and Eclipse restarted, there was no Espressif plugin visible, and other Eclipse settings were changed (e.g., my dark theme changed back to default light).

**Producrt Versions**

Operating System: WIndows 11 (23H2)

Eclipse Version:
Eclipse IDE for C/C++ Developers (includes Incubating components)
Version: 2022-09 (4.25.0)
Build id: 20220908-1902
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 18.0.1+10
Java version: 18.0.1

Espressif ESP IDF Plugin Version (currently installed working version):
Version: 2.11.1.202310270725

**To Reproduce**
1. Go to Help > Check for Updates
2. Select only the Espressif plugin
3. Click buttons to install
4. Eclipse requests restart, so restart
5. Espressif plugin no longer installed and other environment settings have defaulted; the Espressif menu is not available

**Expected behavior**
I expected to reboot Eclipse and the new plugin would be installed and my other environment settings unchanged

**Eclipse Error log:** 
Window > Show View > Other > Search for "Error Log" (Attach as a file)
Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log 

(I will add later)

**Comment by AndriiFilippov** [comment]
@mbratch, hello ! 

Could you please provide the following information to make the investigation faster: 

- your OS
- your Eclipse version
- IDE version of "I was running an older Espressif plugin" 

If you have any questions, feel free to ask.
Thank you !

**Comment by mbratch** [comment]
Hello @AndriiFilippov, thank you for the quick response!

Sorry about the lack of detail in the original post. I didn't have it handy. I updated the description with the requested information.

I also try outright installing the latest plugin as if it were a new install but I got the same results: nothing seemed to install. I had to restore my Eclipse folder from file history to get back to normal.

**Comment by sigmaaa** [comment]
Hi @mbratch, 

thank you for reporting the issue. Based on the information you have provided, it is likely that you have only updated the Espressif plugin without the dependencies required for it to work. To update dependencies as well, you need to go to Help -> Install New Software... -> work with: https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/
![image](https://github.com/espressif/idf-eclipse-plugin/assets/24419842/fdabee00-d9a2-494c-ac9a-0974b5182d36)

**Comment by mbratch** [comment]
Thank you @sigmaaa .

Since I already had a prior version of the Espressif plugin installed, I followed these instructions:

![image](https://github.com/espressif/idf-eclipse-plugin/assets/7990964/f5d45f30-c3e1-4d92-a84d-e9507547fdad)

Do the instructions you linked need updating? I am not sure how I would glean your recommendation from the instructions. I will try your suggestion and see if it works. But since I already have a prior version installed, do I need to remove it first?

**Comment by sigmaaa** [comment]
Hi @mbratch,

thanks for pointing this out, I think this part of the documentation could be improved and we will work on it.
>  But since I already have a prior version installed, do I need to remove it first?

I think that it is not necessary to remove it. After installing/updating the requirements from the "Install New Software..." page and restarting Eclipse, the plugin should work unless an error occurs during installation.

**Comment by mbratch** [comment]
Hi @sigmaaa. When I go to Help -> Install New Software... -> work with: https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/ I get this:

![image](https://github.com/espressif/idf-eclipse-plugin/assets/7990964/082b6cb7-1582-4e5f-ab11-f38f259fa6f4)

**Comment by sigmaaa** [comment]
> Hi @sigmaaa. When I go to Help -> Install New Software... -> work with: https://dl.espressif.com/dl/idf-eclipse-plugin/updates/latest/ I get this:
> 
> ![image](https://user-images.githubusercontent.com/7990964/283935733-082b6cb7-1582-4e5f-ab11-f38f259fa6f4.png)

Hi @mbratch, that's strange. Could you please provide the error log after Eclipse startup? Instructions here https://github.com/espressif/idf-eclipse-plugin#error-log. Thank you.

**Comment by mbratch** [comment]
Hi @sigmaaa . Unfortunately, my Eclipse does not have the Error Log menu:

![image](https://github.com/espressif/idf-eclipse-plugin/assets/7990964/d6d53297-6bee-4268-bdd1-1ab34a5072c9)

**Comment by kolipakakondal** [comment]
> Hi @sigmaaa . Unfortunately, my Eclipse does not have the Error Log menu:
> 


Please click on `Other...` and search for `Error Log`.

Can you also check if you're in `C/C++ perspective`, If you are not in C/C++ perspective the related menu items are not visible.

<img width="271" alt="Screenshot 2023-11-18 at 8 38 14 AM" src="https://github.com/espressif/idf-eclipse-plugin/assets/8463287/5d7fb3c4-59f3-438d-9e81-58a23113a431">

Please also verify, if the IEP plugins installed correctly

Eclipse > About Eclipse > Click on `Installation Details` from the dialog >  Click on `Features` Tab >  Look for `ESP-IDF Eclipse Plugin` 

<img width="759" alt="Screenshot 2023-11-18 at 8 41 31 AM" src="https://github.com/espressif/idf-eclipse-plugin/assets/8463287/04fa1c32-21b8-4152-97f3-d8abe7296f50">

**Note:**
In parallel you can try setting up new environment as it won't take more than 5-10 mins for everything and you should be able to work your existing project.
- Please download latest version of [Espressif-IDE 2.11.1](https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-2.11.1-win32.win32.x86_64.zip)
- Launch with an existing workspace
- Go to `Espressif` Menu > ESP-IDF Tools Manager > Install Tools > 
- Choose your existing IDF directory which you're using earlier, git and python
- Click on `Install Tools` (This won't take much time as tools are already installed earlier, this will set the environement variables and ready the build environment)
- You're good to start with your project again!

Please see that helps!

**Comment by mbratch** [comment]
@kolipakakondal thanks for the tip. I was able to find the Error Log under Show View > Other... > General.

It is attached.
[EclipseError.log](https://github.com/espressif/idf-eclipse-plugin/files/13398956/EclipseError.log)

**Comment by mbratch** [comment]
@kolipakakondal @sigmaaa I just checked the plugin version installed for Espressif and now it appears to be the latest version already. So the system seems to be working. I'm not sure why I had the original error. Thank you for all the direction. I will consider this issue closed for the time being.
