### ISSUE TITLE
怎么加入自己的.h文件 (IEP-189)

### ISSUE THREAD

**Issue by Tangdonghua** [espressif/idf-eclipse-plugin#87]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment Information:** 
Eclipse > About Eclipse > Installation Details > Configuration > Copy to Clipboard (Attach as a file)

**ESP-IDF Tools Information:**
Help > Espressif Tools Manager > List Installed Tools

**Comment by kolipakakondal** [comment]
Hello,
Please follow the below instructions to create a header file.

> Right-click on the main folder in the project >  New > File > test.h
