### ISSUE TITLE
'Install Tools' in 2.12.0 fails with ESP-IDF v5.2 (IEP-1155)

### ISSUE THREAD

**Issue by gregtoth** [espressif/idf-eclipse-plugin#883]
**Describe the bug**
'Install Tools' in 2.12.0 fails with ESP-IDF v5.2 beta releases.
When run Espressif > ESP-IDF Tools Manager > Install Tools, it always ends with Problem Occurred dialog containing the following message:
An internal error occurred during: "Installing tools...".
Cannot invoke "org.eclipse.cdt.core.build.IToolChain.getTypeId()" because "toolchain" is null

Also Preferences... > C/C++ > Core Build Toolchains is missing the Xtensa compiler entries.

Fails with esp-idf-v5.2-beta1 and esp-idf-v5.2-beta2.
Works okay with esp-idf-v5.1.2
Fails for both Espressif-IDF 2.12.0 and Eclipse 2023-12 with plugin 2.12.0 installed.

When using Espressif-IDF 2.11.1, Install Tools with esp-idf-v5.2-beta2 works okay.

**To Reproduce**
1. Delete any existing ~/.espressif directory.
2. Launch Espressif-IDE 2.12.0 or Eclipse 2023-12 with plugin 2.12.0 installed, and create a fresh new workspace.
3. Espressif > ESP-IDF Tools Manager > Install Tools
4. Select directory containing properly downloaded ESP-IDF v5.2-beta1 or v5.2-beta2.
5. Installation fails with Problem Occurred.
6. Inspect Preferences... > C/C++ > Core Build Toolchains and Xtensa entries are missing.

**Expected behavior**
Tools should install successfully and Xtensa toolchain settings should be populated.

When using Espressif-IDF 2.11.1, Install Tools with esp-idf-v5.2-beta2 works okay.

**Screenshots**
![problem-dialog-2 12 0-install-tools-2024-0109](https://github.com/espressif/idf-eclipse-plugin/assets/1812621/1d0a66be-b2e8-4ceb-a98b-4f790a321b8e)

**Espressif-IDE Product Information:**
Espressif-IDF 2.12.0 or Eclipse 2023-12 with ESP-IDF Plugin 2.12.0 installed.

**Eclipse Error log:** 
[error-log-2.12.0-install-tools-2024-0109.log](https://github.com/espressif/idf-eclipse-plugin/files/13878309/error-log-2.12.0-install-tools-2024-0109.log)

**Comment by sigmaaa** [comment]
Hi @gregtoth,

thank you for reporting this. We already have PR for this issue, which will be fixed as soon as possible. I will keep you updated. Thank you

**Comment by BitSalat** [comment]
Same here on WIndows 11 - installation fails, I used latest installer **esp-idf-tools-setup-online-2.24.exe**

![image](https://github.com/espressif/idf-eclipse-plugin/assets/62297904/8aaa1693-ff53-4efb-a298-888400901724)

**Comment by alirana01** [comment]
The fix is in the master should be out with the new release. Feel free to open the issue if it happens after the upcoming release @gregtoth @BitSalat

**Comment by BitSalat** [comment]
Any idea when there will be the new release?

**Comment by kolipakakondal** [comment]
Hi @BitSalat Next release will be most likely in the mid of Feb.
