### ISSUE TITLE
Unresolved Inclusion on base installation of ESP-IDF on Eclipse on Windows 10 (IEP-193)

### ISSUE THREAD

**Issue by SilentPotat0** [espressif/idf-eclipse-plugin#89]
**Describe the bug**
I followed the guide for the automated install and ran the steps for the eclipse setup and it appears everything worked, intill i opened up the template project and it couldnt find any of the the includes

**To Reproduce**
install the esp eclipse plugin following the steps descriped in the readme.md

**Expected behavior**
expected it to come with the template includes already set up, and if not a section about setiing them up, since i do not know how :)

**Screenshots**
![image](https://user-images.githubusercontent.com/48694729/83182880-4fa17800-a127-11ea-8443-954890e70bbe.png)

**Environment Information:** 
[eclipse_config.txt](https://github.com/espressif/idf-eclipse-plugin/files/4697672/eclipse_config.txt)

**ESP-IDF Tools Information:**
doesnt want to tell me anything, nothing happens

**Comment by kolipakakondal** [comment]
Hi @SilentPotat0 

- Looks like you don't have the latest version of a plugin - please get the latest using the update site
- Unresolved inclusion errors will disappear only after the build. Is the build successful?
- Have you installed the tools from eclipse? Any issues reported?

**Comment by SilentPotat0** [comment]
nvm today it apparently works fine, even tried rebooting yesterday so dont know why. sorry for wasting your time :)
