### ISSUE TITLE
[Debian 12, Eclipse IDF 2023-12, ESP-IDF Plugin 2.12] ESP-IDF Tools manager > Install Tools errors.  (IEP-1168)

### ISSUE THREAD

**Issue by GTCLive** [espressif/idf-eclipse-plugin#898]
**Environment:** 
Linux Debian 12 (Bookworm, kernel: 6.1.0-17)
Eclipse IDE for C/C++ Developers
Version: 2023-12 (4.30.0)
Build id: 20231201-2043
Espressif IDF Plugins for Eclipse	2.12.0.202312220530

**Steps to reproduce:**
Eclipse IDE (Top menu) > Espressif > ESP-IDF Tools manager > Install Tools

**Error Log:** [2023-12-Install Tools Log.txt](https://github.com/espressif/idf-eclipse-plugin/files/14174683/2023-12-Install.Tools.Log.txt)

![2023-12-IDF](https://github.com/espressif/idf-eclipse-plugin/assets/91785220/3360dcec-ac7d-4bab-845e-2040966997bb)

**Comment by diplfranzhoepfinger** [comment]
same here!

this happens only with esp-idf master, not with esp-idf 5.1.2

**Comment by diplfranzhoepfinger** [comment]
this seems to be an esp-idf Problem

**Comment by GTCLive** [comment]
Fixes the qemu error and missing dependency:
`$ sudo apt install libslirp0`

**Comment by GTCLive** [comment]
Fixes the qemu error and missing dependency:
$ sudo apt install libslirp0

**Comment by diplfranzhoepfinger** [comment]
```
sudo apt install libslirp0
```

**Comment by diplfranzhoepfinger** [comment]
espressif/esp-idf#13152
