### ISSUE TITLE
After installing esp-idf in eclipse on macOS, it asks for "full screen recording permission" (IEP-194)

### ISSUE THREAD

**Issue by incyi** [espressif/idf-eclipse-plugin#90]
**Describe the bug**
After installing esp-idf(Espressif IDF 1.0.0.47I1cKb_nh773733993535E) in eclipse 2020-03(2020-03 (4.15.0)) on macOS(10.15.5), it asks for "full screen recording permission". 

**To Reproduce**
1. Install Eclipse
2. Install ESP-IDF plugin
3. Restart Eclipse
4. See pop-up from macOS asking for permission.

**Expected behavior**
Why does esp-idf needs full screen recording ?

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/1822795/83241250-d8a5c700-a19a-11ea-92c6-8ce212ff78f2.png)

**Environment Information:** 
(I think this is not needed for now)

**ESP-IDF Tools Information:**
Executing /usr/bin/python /opt/esp/esp-idf/tools/idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2020r1-8.2.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2020r1-8.2.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20200420 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.0 (recommended, installed)

**Comment by kolipakakondal** [comment]
Hi @incyi - Thanks for reporting. 

I know from macOS Catalina, Apple has added a new Screen Recording permission that needs to be granted to every application that tries to record the screen. 

The question here is why the eclipse is requesting screen recording permission. I'm sure this is nothing to do with the idf eclipse plugin. Need to be investigated from the Eclipse installer. I couldn't find anything in the eclipse Bugzilla as well. If you see this issue with eclipse without installing the IDF plugin - please report this here https://bugs.eclipse.org/bugs/
