### ISSUE TITLE
Abort build process in presence of errors (IEP-1180)

### ISSUE THREAD

**Issue by LemonBoy** [espressif/idf-eclipse-plugin#912]
When the build runner runs Make/Ninja and correctly detects the presence of one or more errors the build process should be aborted earlier.

At the moment the [code](https://github.com/espressif/idf-eclipse-plugin/blob/376b4845c4925039b9db6f60c5099687bfa42d86/bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java#L449) is blindly continuing as if the binary was successfully build and goes on calling `idf_size.py` on a stale map file and, what's worse, dumps the output of `idf_size.py` in the console window, hiding the red lines pointing to the error.

**Comment by sigmaaa** [comment]
Hi @LemonBoy,

that's a good point! Thank you for reporting this.
