### ISSUE TITLE
Move 'ESP-IDF: ****' context menu items into 'ESP-IDF' SUBMENU instead of putting them on top level (IEP-1236)

### ISSUE THREAD

**Issue by powerbroker** [espressif/idf-eclipse-plugin#956]
![ESP-IDF menu usability](https://github.com/espressif/idf-eclipse-plugin/assets/2069825/2cffdc88-8020-40d1-88f8-464e2de6e3e8)

When context menu cannot completely reside within screen area, it just sucks.

From another side there is absolutely no reason to put all of them on top level. The ''ESP-IDF:' prefix implies: they all must be UNDER the "ESP-IDF" submenu.

**Comment by kolipakakondal** [comment]
Hi @powerbroker Agree with you. We are working on this, it will be part of the next release.

**Comment by kolipakakondal** [comment]
This is fixed in the (https://github.com/espressif/idf-eclipse-plugin/releases/tag/v3.0.0-beta2 release, where all the menu items moved to ESP-IDF main menu.

![image](https://github.com/espressif/idf-eclipse-plugin/assets/8463287/804784a6-a337-4783-a843-ef096b1b78b8)

**Comment by kolipakakondal** [comment]
This is fixed in the v3.0.0 release, hence closing the issue.
https://github.com/espressif/idf-eclipse-plugin/releases/tag/v3.0.0

**Comment by powerbroker** [comment]
verified, OK
