### ISSUE TITLE
com.espressif.idf.core.idfNature resource key must have matching localized string value (IEP-1238)

### ISSUE THREAD

**Issue by powerbroker** [espressif/idf-eclipse-plugin#958]
![ESP-IDF project nature](https://github.com/espressif/idf-eclipse-plugin/assets/2069825/ff4fa734-b1dc-492c-a313-62f71331f7ff)

The project natures dialog must show user-friendly localized name instead of i18n resource key.

**Comment by kolipakakondal** [comment]
This is fixed v3.1.0
