### ISSUE TITLE
No longer able to create a project from template???? (IEP-202)

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [espressif/idf-eclipse-plugin#97]
I just deleted 3 sample projects that were all created from templates.... 

When I start fresh again -- the wizard interface won't allow me to "Next"

<img width="523" alt="NoNext" src="https://user-images.githubusercontent.com/26010899/84134250-e13fac80-aa7a-11ea-8eea-dddddad4773b.png">

Even when I restart Eclipse -- I still can't get back to the templates.   What did I do wrong?

When I continue to "Finish" without being able to select from a template -- I get a new error.

<img width="429" alt="Periodic" src="https://user-images.githubusercontent.com/26010899/84134603-675bf300-aa7b-11ea-87e7-57dc664bd4fd.png">

This may have something to do with the deleting of the metadata directory which I did previously to make the working directory completely clean.

**Comment by SolidStateLEDLighting** [comment]
I figured out what I needed to do.    I had to go through the steps of installing the esp tools again and setting the path variables as seen in the instructions just before project creation.    That set up the system to allow me again to access the templates for project building...

BUT   BUT -- now I'm getting a  "No Toolchain found for Target Local"

**Comment by SolidStateLEDLighting** [comment]
My tool allows me to create a new project with a template -- but it won't build -- and I'm not allowed to edit the launch configuration.

The complaint is "No Toolchain found for Target Local"

I don't even know at this point how to get the entire build environment working again....

**Comment by SolidStateLEDLighting** [comment]
NOTE --- when generating a launch target -- the tool doesn't offer me the IDF Target drop-down box.    Looks like it is not aware of my idf project classification.

**Comment by kolipakakondal** [comment]
> "No Toolchain found for Target Local"

The issue could be this https://github.com/espressif/idf-eclipse-plugin/blob/master/FAQ.md#no-esp-launch-target-found-please-createselect-the-correct-launch-target-error

Make sure you've created esp launch target and selected during the build

**Comment by SolidStateLEDLighting** [comment]
The log in the metadata table (project directly) is full of java.lang.NullPointerExceptions

**Comment by SolidStateLEDLighting** [comment]
That comment above is interesting -- because there was not launch target at the time.   Normally you work from left to right to complete a sequence and I wasn't at that point.

I did jump ahead and created a target - then went back build and it said that it couldn't find the launch target. (even though I had just created one).

**Comment by kolipakakondal** [comment]
> The log in the metadata table (project directly) is full of java.lang.NullPointerExceptions

I think your workspace is corrupted since you've modified the .metadata. I would suggest to create a new workspace and import the existing project

**Comment by SolidStateLEDLighting** [comment]
I don't need to import any existing -- I'll just try to get started from scratch again.   I think you much run the "import tools" set when you create a new workspace.

**Comment by SolidStateLEDLighting** [comment]
We would be told "Hey -- don't delete the metadata"

**Comment by SolidStateLEDLighting** [comment]
I have no idea how to create a new workspace

**Comment by kolipakakondal** [comment]
File > Switch Workspace > Other

**Comment by SolidStateLEDLighting** [comment]
I see that...  Thank youl.

**Comment by SolidStateLEDLighting** [comment]
I have a new workspace.   I asked to install tools again to supply idf path and git.exe path.  

When I started a new project I can't build it... I get "No Toolchain found for Target Local" and the launch configuration will not open in edit mode.     What am I doing wrong?

**Comment by SolidStateLEDLighting** [comment]
Forgot to create a launch target.... Created what I think the right launch target - now I get

No esp launch target found. Please create/select the correct 'Launch Target'

**Comment by kolipakakondal** [comment]
I'm sorry, did you follow these steps?
https://github.com/espressif/idf-eclipse-plugin#configuring-launch-target

<img width="274" alt="Screenshot 2020-06-09 at 4 48 32 PM" src="https://user-images.githubusercontent.com/8463287/84141631-18a95b80-aa71-11ea-9f65-213948c22b51.png">

**Comment by SolidStateLEDLighting** [comment]
<img width="733" alt="LaunchTarget" src="https://user-images.githubusercontent.com/26010899/84141891-75634100-aa86-11ea-86d5-9fba8ab24941.png">

**Comment by SolidStateLEDLighting** [comment]
It never prompted me with that dialog box.

**Comment by SolidStateLEDLighting** [comment]
WAIT -- Ok, I missed that step.     I see now that I much do this manually just after creating the project.   Let me try this again.

**Comment by SolidStateLEDLighting** [comment]
It worked this time... boy -- that is a very big stumbling point.....  If you don't follow that exactly -- then you're hosed up big time.

**Comment by SolidStateLEDLighting** [comment]
The project is building....

**Comment by kolipakakondal** [comment]
See if this helps https://youtu.be/DqnZy4d03_s

Check the demo part

**Comment by SolidStateLEDLighting** [comment]
Already watched that video..

**Comment by SolidStateLEDLighting** [comment]
I see him doing a lot more in the launch configuration area.... I need to study that again... I may have stopped the vide prior to that area -- or I was so swamped by all the new info that I could not remember what had done there.

**Comment by SolidStateLEDLighting** [comment]
My Hello-World project is running.   I just need to gain enough understanding of renaming a project and managing several projects to get this under control.

**Comment by SolidStateLEDLighting** [comment]
RECOMMENDATION.... if creating a Launch Target is critical to not breaking the Launch Configuration area -- you should put the Launch Target window to the left of the Configuration window because you can easily forget this operational order.

**Comment by SolidStateLEDLighting** [comment]
You helped me a great deal today.     I'm not quite there yet -- but I see the error of my ways in not creating the Launch Target first.   Thank you very much.    I hope you guys can really get this plug-in nailed down because I'd like to stay with Eclipse and see if the tool proves out for ESP development.
