### ISSUE TITLE
Can't delete a Launch Target (IEP-203)

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [espressif/idf-eclipse-plugin#98]
This issue is pretty simple -- there is no intuitive way to delete any ESP32 launch targets.   I have a mess to clean up because made a launch target in an incorrect way -- how do I destroy one?

**Comment by nasscube** [comment]
@SolidStateLEDLighting Did you find a solution ? 
Anybody knows how to delete a launch target on Eclipse ?

**Comment by SolidStateLEDLighting** [comment]
I dumped your tool and I develop with VS2019 now.
 
--------- Original Message --------- Subject: Re: [espressif/idf-eclipse-plugin] Can't delete a Launch Target (IEP-203) (#98)

**Comment by JKSAR** [comment]
Hi @SolidStateLEDLighting, I found a way.

In ESP Application chose the launch target and click with right button, then select DELETE

![image](https://user-images.githubusercontent.com/51222937/109075275-ac8e8680-76d7-11eb-9039-7b3bbfa68cdb.png)

**Comment by sigmaaa** [comment]
The option to delete a launch target was added. You can find related changes in [2.2.0 release ](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.2.0). To delete the launch target, just click on the wheel on the launch target that you want to delete and click on the "Delete" button:

<img width="593" alt="Screenshot 2021-08-17 at 12 23 57" src="https://user-images.githubusercontent.com/24419842/129700205-029ce603-37d7-4f85-a279-210b76d22a1c.png">
