### ISSUE TITLE
Launch Configurations remain hidden when projects are opened after startup (IEP-204)

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [espressif/idf-eclipse-plugin#99]
Forward Notice:  I'm very impressed with the development idf-eclipse-plugin.  You guys (and gals) have done a fine job.   It is just a little bit quirky in a few subtle ways that look like bugs in the workflow.

I have been working through the usability of the tool --- changing workspaces and projects.   The tool hides Launch Configurations of projects which are not open by default upon restarting of the application.    This same condition also tends to present when you are changing workspaces.

WORKAROUND -- if you restart Eclipse with target projects already open, then the Launch Configurations are on the drop-down list -- but all closed project's Launch Configurations are hidden.

ALSO -- You find that often the tool will not remember the Git Executable Location.

NOTE:   Looks like none of this is an issue of you always leave all the projects open in all workspaces.    What is the benefit in closing a project in a workspace?   Why allow a user to close a project (closed folder)?

**Expected behavior**
All Launch configurations should be added to the drop-down box for any projects that are opened.

**Screenshots**
Self Evident

**Environment Information:** 
Window Env --- 2020-03 build.

**ESP-IDF Tools Information:**
All current tools as I try to reload them in the testing to effect positive change.

**Comment by kolipakakondal** [comment]
The closed project concept is from the Eclipse. This is useful a lot for the developers if you're having multiple projects in the workspace and some of them are not needed at this moment so you can just hide them.

We will check the other issues which you've reported here - Git executable location and Launch Configurations discrepancies.

Thank you so much for your feedback, really appreciate it!

**Comment by sigmaaa** [comment]
`Launch Configurations Bar` is updating dynamically since [2.3](https://github.com/espressif/idf-eclipse-plugin/releases/tag/v2.3.0)
