### ISSUE TITLE
Espressi-IDE 3.0.0 doesn't highlight inactive code (IEP-1263)

### ISSUE THREAD

**Issue by dariomingarelli** [espressif/idf-eclipse-plugin#994]
Espressi-IDE 3.0.0 doesn't highlight inactive code.
I use a lot of #define and #ifdef, till 2.12.1 the inactive code were highlighted (for example, in black background for dark mode), now there is no way to have this working.

I've also tried to restore or modify the highlight color in:
Espressi-IDE > Preferences > C/C++ > Editor
And manage "Inactive code highlight" under "Appearance color options:".

**Comment by luciantodor** [comment]
I subscribe to this issue. The inactive code is not highlighted at all.

**Comment by ifedotov1984** [comment]
> This is fixed with the v3.1.0 release which comes with the CDT LSP 2.0 which has the support for inactive code is highlight

Still do not work in Dark Theme (in Light all is ok)
![image](https://github.com/user-attachments/assets/5735f4d2-82c5-478f-ba60-a73b36dac677)

**Comment by kolipakakondal** [comment]
Ok, thanks for verifying and letting us know. Let us check.
